export const activitiesKeywords: Record<string, string[]> = {
    // ── Activities ──
    '⚽': ['soccer', 'football', 'ball', 'sport', 'game'],
    '🏀': ['basketball', 'ball', 'sport', 'game', 'nba'],
    '🏈': ['football', 'american', 'ball', 'sport', 'nfl'],
    '⚾': ['baseball', 'ball', 'sport', 'game'],
    '🥎': ['softball', 'ball', 'sport', 'game'],
    '🎾': ['tennis', 'ball', 'sport', 'racket'],
    '🏐': ['volleyball', 'ball', 'sport', 'game'],
    '🏉': ['rugby', 'ball', 'sport', 'game'],
    '🥏': ['frisbee', 'disc', 'sport', 'flying'],
    '🎱': ['pool', 'billiards', 'ball', 'eight', 'game'],
    '🏓': ['ping', 'pong', 'table tennis', 'sport', 'paddle'],
    '🏸': ['badminton', 'racket', 'shuttlecock', 'sport'],
    '🏒': ['hockey', 'ice', 'stick', 'puck', 'sport'],
    '🏑': ['field', 'hockey', 'stick', 'sport'],
    '🥍': ['lacrosse', 'stick', 'sport'],
    '🏏': ['cricket', 'bat', 'sport', 'game'],
    '🪃': ['boomerang', 'throw', 'return', 'australia'],
    '🥅': ['goal', 'net', 'sport', 'score'],
    '⛳': ['golf', 'flag', 'hole', 'sport'],
    '🪁': ['kite', 'fly', 'wind', 'outdoor'],
    '🎣': ['fishing', 'rod', 'fish', 'hobby', 'outdoor'],
    '🤿': ['diving', 'mask', 'snorkel', 'swim', 'underwater'],
    '🎽': ['running', 'shirt', 'jersey', 'sport', 'athletic'],
    '🎿': ['ski', 'skiing', 'snow', 'winter', 'sport'],
    '🛷': ['sled', 'sledge', 'snow', 'winter', 'slide'],
    '🥌': ['curling', 'stone', 'ice', 'sport', 'winter'],
    '🎯': ['target', 'dart', 'bullseye', 'aim', 'goal'],
    '🪀': ['yoyo', 'toy', 'play', 'string'],
    '🪆': ['nesting', 'dolls', 'matryoshka', 'russian', 'toy'],
    '🎮': ['game', 'controller', 'gaming', 'video', 'play', 'console'],
    '🎲': ['dice', 'game', 'chance', 'luck', 'roll', 'board'],
    '🧩': ['puzzle', 'piece', 'jigsaw', 'game', 'solve'],
    '🧸': ['teddy', 'bear', 'toy', 'stuffed', 'plush', 'cute'],
    '🪅': ['pinata', 'party', 'candy', 'celebration'],
    '🎭': ['theater', 'drama', 'masks', 'performing', 'arts'],
    '🎨': ['art', 'paint', 'palette', 'creative', 'draw', 'color'],
    '🎬': ['movie', 'film', 'clapper', 'cinema', 'action'],
    '🎤': ['microphone', 'sing', 'karaoke', 'music', 'voice'],
    '🎧': ['headphones', 'music', 'listen', 'audio', 'earphones'],
    '🎼': ['music', 'score', 'notes', 'sheet', 'compose'],
    '🎵': ['music', 'note', 'song', 'melody', 'tune'],
    '🎶': ['music', 'notes', 'song', 'melody', 'tune'],
    '🎷': ['saxophone', 'sax', 'jazz', 'music', 'instrument'],
    '🎸': ['guitar', 'rock', 'music', 'instrument', 'string'],
    '🎹': ['piano', 'keyboard', 'music', 'instrument', 'keys'],
    '🎺': ['trumpet', 'brass', 'music', 'instrument', 'horn'],
    '🎻': ['violin', 'fiddle', 'music', 'instrument', 'string'],
    '🥁': ['drum', 'music', 'instrument', 'beat', 'percussion'],
    '🪘': ['drum', 'long', 'music', 'instrument', 'african'],
    '🎙': ['microphone', 'studio', 'record', 'podcast', 'radio'],
    '📻': ['radio', 'music', 'broadcast', 'listen'],
    '🎚': ['slider', 'level', 'audio', 'volume', 'control'],
    '🎛': ['knobs', 'control', 'dials', 'audio', 'mixing'],
    '📺': ['television', 'tv', 'screen', 'watch', 'show'],
    '📷': ['camera', 'photo', 'picture', 'photography'],
    '📸': ['camera', 'flash', 'photo', 'picture', 'snapshot'],
    '🎥': ['camera', 'movie', 'film', 'video', 'record'],
    '🎞': ['film', 'frames', 'movie', 'cinema', 'reel'],
    '📽': ['projector', 'film', 'movie', 'cinema', 'presentation'],
    '🎦': ['cinema', 'movie', 'theater', 'screen'],
    '🏋️': ['weightlifting', 'gym', 'exercise', 'strong', 'fitness'],
    '🤼': ['wrestling', 'sport', 'fight', 'grapple'],
    '🤸': ['cartwheel', 'gymnastics', 'acrobat', 'flip'],
    '🤺': ['fencing', 'sword', 'sport', 'duel'],
    '⛹️': ['basketball', 'bounce', 'dribble', 'sport'],
    '🤾': ['handball', 'sport', 'throw', 'ball'],
    '🏌️': ['golf', 'swing', 'club', 'sport'],
    '🏇': ['horse', 'racing', 'jockey', 'sport', 'ride'],
    '🧘': ['yoga', 'meditate', 'zen', 'lotus', 'mindfulness'],
    '🏄': ['surfing', 'surf', 'wave', 'ocean', 'beach'],
    '🏊': ['swimming', 'swim', 'pool', 'water', 'sport'],
    '🤽': ['water', 'polo', 'swim', 'sport', 'ball'],
    '🚣': ['rowing', 'boat', 'paddle', 'water', 'canoe'],
    '🧗': ['climbing', 'rock', 'sport', 'mountain', 'wall'],
    '🚵': ['mountain', 'biking', 'cycling', 'bike', 'sport'],

};
