export const animalsKeywords: Record<string, string[]> = {
    // ── Animals ──
    '🐶': ['dog', 'puppy', 'pet', 'animal', 'cute'],
    '🐱': ['cat', 'kitten', 'pet', 'animal', 'cute'],
    '🐭': ['mouse', 'rat', 'rodent', 'animal'],
    '🐹': ['hamster', 'pet', 'rodent', 'animal', 'cute'],
    '🐰': ['rabbit', 'bunny', 'pet', 'animal', 'cute'],
    '🦊': ['fox', 'animal', 'wild', 'clever'],
    '🐻': ['bear', 'animal', 'wild', 'brown'],
    '🐼': ['panda', 'bear', 'animal', 'bamboo', 'china'],
    '🐻‍❄️': ['polar', 'bear', 'arctic', 'ice', 'white'],
    '🐨': ['koala', 'animal', 'australia', 'cute'],
    '🐯': ['tiger', 'animal', 'wild', 'cat', 'stripe'],
    '🦁': ['lion', 'animal', 'wild', 'king', 'mane'],
    '🐮': ['cow', 'animal', 'farm', 'milk', 'moo'],
    '🐷': ['pig', 'animal', 'farm', 'oink'],
    '🐸': ['frog', 'animal', 'toad', 'green', 'ribbit'],
    '🐵': ['monkey', 'animal', 'ape', 'primate'],
    '🙈': ['see', 'no', 'evil', 'monkey', 'eyes', 'hide'],
    '🙉': ['hear', 'no', 'evil', 'monkey', 'ears'],
    '🙊': ['speak', 'no', 'evil', 'monkey', 'mouth'],
    '🐔': ['chicken', 'hen', 'bird', 'farm', 'poultry'],
    '🐧': ['penguin', 'bird', 'animal', 'arctic', 'cold'],
    '🐦': ['bird', 'animal', 'fly', 'tweet'],
    '🐤': ['chick', 'baby', 'bird', 'chicken', 'cute'],
    '🦆': ['duck', 'bird', 'animal', 'quack', 'water'],
    '🦅': ['eagle', 'bird', 'animal', 'fly', 'america'],
    '🦉': ['owl', 'bird', 'night', 'wise', 'hoot'],
    '🦇': ['bat', 'animal', 'vampire', 'night', 'fly'],
    '🐺': ['wolf', 'animal', 'wild', 'howl'],
    '🐗': ['boar', 'pig', 'wild', 'animal'],
    '🐴': ['horse', 'animal', 'ride', 'pony'],
    '🦄': ['unicorn', 'horse', 'magic', 'fantasy', 'rainbow'],
    '🐝': ['bee', 'honey', 'insect', 'buzz', 'sting'],
    '🪱': ['worm', 'insect', 'earth', 'crawl'],
    '🐛': ['bug', 'insect', 'caterpillar', 'crawl'],
    '🦋': ['butterfly', 'insect', 'beautiful', 'wings', 'nature'],
    '🐌': ['snail', 'slow', 'animal', 'shell'],
    '🐞': ['ladybug', 'insect', 'beetle', 'red', 'luck'],
    '🐜': ['ant', 'insect', 'small', 'colony'],
    '🪲': ['beetle', 'insect', 'bug'],
    '🦟': ['mosquito', 'insect', 'bug', 'bite'],
    '🦗': ['cricket', 'insect', 'chirp', 'grasshopper'],
    '🕷': ['spider', 'insect', 'web', 'arachnid'],
    '🦂': ['scorpion', 'arachnid', 'sting', 'desert'],
    '🐢': ['turtle', 'tortoise', 'animal', 'slow', 'shell'],
    '🐍': ['snake', 'reptile', 'animal', 'hiss'],
    '🦎': ['lizard', 'reptile', 'animal', 'gecko'],
    '🦖': ['dinosaur', 'trex', 'extinct', 'reptile', 'jurassic'],
    '🦕': ['dinosaur', 'sauropod', 'extinct', 'brontosaurus'],
    '🐙': ['octopus', 'sea', 'ocean', 'tentacle', 'marine'],
    '🦑': ['squid', 'sea', 'ocean', 'tentacle', 'marine'],
    '🦐': ['shrimp', 'prawn', 'seafood', 'ocean'],
    '🦞': ['lobster', 'seafood', 'ocean', 'crustacean'],
    '🦀': ['crab', 'seafood', 'ocean', 'crustacean', 'beach'],
    '🐡': ['blowfish', 'puffer', 'fish', 'ocean', 'sea'],
    '🐠': ['fish', 'tropical', 'ocean', 'sea', 'aquarium'],
    '🐟': ['fish', 'ocean', 'sea', 'aquatic'],
    '🐬': ['dolphin', 'ocean', 'sea', 'marine', 'smart'],
    '🐳': ['whale', 'ocean', 'sea', 'marine', 'spout'],
    '🐋': ['whale', 'ocean', 'sea', 'marine', 'humpback'],
    '🦈': ['shark', 'ocean', 'sea', 'fish', 'danger'],
    '🐊': ['crocodile', 'alligator', 'reptile', 'swamp'],
    '🐅': ['tiger', 'animal', 'wild', 'cat', 'stripe'],
    '🐆': ['leopard', 'animal', 'wild', 'cat', 'spots', 'cheetah'],
    '🦓': ['zebra', 'animal', 'stripe', 'africa'],
    '🦍': ['gorilla', 'ape', 'primate', 'animal', 'strong'],
    '🦧': ['orangutan', 'ape', 'primate', 'animal'],
    '🦣': ['mammoth', 'elephant', 'extinct', 'ice age', 'woolly'],
    '🐘': ['elephant', 'animal', 'large', 'trunk', 'africa'],
    '🦛': ['hippo', 'hippopotamus', 'animal', 'water', 'africa'],
    '🦏': ['rhino', 'rhinoceros', 'animal', 'horn', 'africa'],
    '🐪': ['camel', 'desert', 'animal', 'hump'],
    '🐫': ['camel', 'desert', 'animal', 'two humps', 'bactrian'],
    '🦒': ['giraffe', 'animal', 'tall', 'africa', 'spots'],
    '🦘': ['kangaroo', 'animal', 'australia', 'jump', 'pouch'],
    '🦬': ['bison', 'buffalo', 'animal', 'wild'],

};
