export const foodKeywords: Record<string, string[]> = {
    // ── Food ──
    '🍎': ['apple', 'fruit', 'red', 'healthy'],
    '🍊': ['orange', 'tangerine', 'fruit', 'citrus'],
    '🍋': ['lemon', 'citrus', 'fruit', 'sour', 'yellow'],
    '🍇': ['grapes', 'fruit', 'wine', 'purple'],
    '🍓': ['strawberry', 'fruit', 'berry', 'red'],
    '🫐': ['blueberry', 'berry', 'fruit'],
    '🍈': ['melon', 'fruit', 'green', 'honeydew'],
    '🍒': ['cherry', 'cherries', 'fruit', 'red'],
    '🍑': ['peach', 'fruit', 'pink'],
    '🥭': ['mango', 'fruit', 'tropical'],
    '🍍': ['pineapple', 'fruit', 'tropical'],
    '🥥': ['coconut', 'fruit', 'tropical', 'palm'],
    '🥝': ['kiwi', 'fruit', 'green'],
    '🍅': ['tomato', 'vegetable', 'red', 'fruit'],
    '🍆': ['eggplant', 'aubergine', 'vegetable', 'purple'],
    '🥑': ['avocado', 'fruit', 'green', 'guacamole'],
    '🥦': ['broccoli', 'vegetable', 'green', 'healthy'],
    '🥬': ['leafy', 'green', 'vegetable', 'lettuce', 'salad'],
    '🥒': ['cucumber', 'vegetable', 'green', 'pickle'],
    '🌶': ['pepper', 'chili', 'hot', 'spicy', 'red'],
    '🫑': ['bell', 'pepper', 'vegetable', 'green'],
    '🧄': ['garlic', 'vegetable', 'cooking', 'spice'],
    '🧅': ['onion', 'vegetable', 'cooking', 'cry'],
    '🥔': ['potato', 'vegetable', 'starch', 'spud'],
    '🍠': ['sweet', 'potato', 'yam', 'vegetable'],
    '🥐': ['croissant', 'bread', 'pastry', 'french', 'breakfast'],
    '🥯': ['bagel', 'bread', 'breakfast'],
    '🍞': ['bread', 'loaf', 'toast', 'baking'],
    '🥖': ['baguette', 'bread', 'french'],
    '🥨': ['pretzel', 'bread', 'snack', 'salty'],
    '🧀': ['cheese', 'dairy', 'swiss', 'yellow'],
    '🥚': ['egg', 'food', 'breakfast', 'chicken'],
    '🍳': ['egg', 'fried', 'cooking', 'breakfast', 'pan'],
    '🧈': ['butter', 'dairy', 'spread', 'cooking'],
    '🥞': ['pancake', 'breakfast', 'stack', 'syrup'],
    '🧇': ['waffle', 'breakfast', 'syrup'],
    '🥓': ['bacon', 'meat', 'pork', 'breakfast'],
    '🥩': ['meat', 'steak', 'beef', 'cut'],
    '🍗': ['chicken', 'leg', 'poultry', 'drumstick', 'meat'],
    '🍖': ['meat', 'bone', 'rib'],
    '🌭': ['hotdog', 'sausage', 'fast food'],
    '🍔': ['burger', 'hamburger', 'fast food', 'cheeseburger'],
    '🍟': ['fries', 'french', 'chips', 'fast food', 'potato'],
    '🍕': ['pizza', 'slice', 'italian', 'cheese', 'fast food'],
    '🌮': ['taco', 'mexican', 'food', 'shell'],
    '🌯': ['burrito', 'wrap', 'mexican', 'food'],
    '🫔': ['tamale', 'mexican', 'food', 'corn'],
    '🥙': ['pita', 'falafel', 'kebab', 'wrap', 'stuffed'],
    '🧆': ['falafel', 'food', 'middle eastern', 'chickpea'],
    '🍜': ['noodles', 'ramen', 'soup', 'asian', 'bowl'],
    '🍝': ['spaghetti', 'pasta', 'italian', 'noodles'],
    '🍣': ['sushi', 'japanese', 'fish', 'rice'],
    '🍱': ['bento', 'box', 'japanese', 'lunch', 'meal'],
    '🍛': ['curry', 'rice', 'indian', 'food', 'spicy'],
    '🍲': ['stew', 'pot', 'soup', 'food', 'cooking'],
    '🥘': ['paella', 'pan', 'cooking', 'food', 'shallow'],
    '🫕': ['fondue', 'cheese', 'pot', 'swiss', 'melted'],
    '🍦': ['ice cream', 'cone', 'dessert', 'cold', 'sweet'],
    '🍧': ['shaved', 'ice', 'dessert', 'cold', 'sweet'],
    '🍨': ['ice cream', 'sundae', 'dessert', 'sweet'],
    '🍩': ['donut', 'doughnut', 'dessert', 'sweet', 'pastry'],
    '🍪': ['cookie', 'biscuit', 'dessert', 'sweet', 'baking'],
    '🎂': ['cake', 'birthday', 'candles', 'celebration', 'dessert'],
    '🍰': ['cake', 'slice', 'shortcake', 'dessert', 'sweet'],
    '🧁': ['cupcake', 'muffin', 'dessert', 'sweet', 'baking'],
    '🥧': ['pie', 'dessert', 'baking', 'apple'],
    '🍫': ['chocolate', 'bar', 'candy', 'sweet'],
    '🍬': ['candy', 'sweet', 'sugar', 'wrapped'],
    '🍭': ['lollipop', 'candy', 'sweet', 'sugar'],
    '🍮': ['pudding', 'custard', 'flan', 'dessert'],
    '🍯': ['honey', 'pot', 'sweet', 'bee'],
    '🍵': ['tea', 'cup', 'green', 'drink', 'hot'],
    '☕': ['coffee', 'cup', 'drink', 'hot', 'cafe', 'espresso'],
    '🧃': ['juice', 'box', 'drink', 'beverage'],
    '🥤': ['cup', 'straw', 'soda', 'drink', 'beverage'],
    '🧋': ['boba', 'bubble', 'tea', 'milk', 'drink'],
    '🍺': ['beer', 'mug', 'drink', 'alcohol', 'bar'],
    '🍻': ['beer', 'cheers', 'clink', 'drink', 'toast'],
    '🥂': ['champagne', 'cheers', 'toast', 'wine', 'celebrate'],
    '🍷': ['wine', 'glass', 'red', 'drink', 'alcohol'],
    '🥃': ['whiskey', 'tumbler', 'drink', 'alcohol', 'glass'],
    '🍸': ['cocktail', 'martini', 'drink', 'alcohol', 'glass'],
    '🍹': ['tropical', 'drink', 'cocktail', 'alcohol', 'umbrella'],
    '🧉': ['mate', 'drink', 'tea', 'argentina'],
    '🍾': ['champagne', 'bottle', 'celebrate', 'pop', 'cork'],

};
