export const objectsKeywords: Record<string, string[]> = {
    // ── Objects ──
    '⌚': ['watch', 'time', 'clock', 'wrist', 'accessory'],
    '📱': ['phone', 'mobile', 'smartphone', 'cell', 'iphone'],
    '💻': ['laptop', 'computer', 'pc', 'mac', 'work'],
    '🖥': ['desktop', 'computer', 'monitor', 'screen', 'display'],
    '🖨': ['printer', 'print', 'paper', 'office'],
    '⌨️': ['keyboard', 'type', 'computer', 'input'],
    '🖱': ['mouse', 'computer', 'click', 'cursor'],
    '🖲': ['trackball', 'computer', 'input', 'device'],
    '💾': ['floppy', 'disk', 'save', 'storage', 'retro'],
    '💿': ['cd', 'disc', 'dvd', 'music', 'optical'],
    '📀': ['dvd', 'disc', 'movie', 'video', 'optical'],
    '📹': ['video', 'camera', 'camcorder', 'record'],
    '📞': ['telephone', 'phone', 'receiver', 'call'],
    '☎️': ['telephone', 'phone', 'vintage', 'call', 'retro'],
    '⏰': ['alarm', 'clock', 'time', 'wake', 'morning'],
    '⌛': ['hourglass', 'time', 'sand', 'timer', 'done'],
    '⏳': ['hourglass', 'time', 'sand', 'timer', 'flowing'],
    '📡': ['satellite', 'dish', 'signal', 'antenna', 'broadcast'],
    '🔋': ['battery', 'power', 'charge', 'energy'],
    '🔌': ['plug', 'electric', 'power', 'outlet', 'charge'],
    '💡': ['bulb', 'light', 'idea', 'bright', 'lamp'],
    '🔦': ['flashlight', 'torch', 'light', 'beam'],
    '🕯': ['candle', 'light', 'flame', 'wax'],
    '🪔': ['lamp', 'oil', 'diya', 'light', 'flame'],
    '🧯': ['fire', 'extinguisher', 'safety', 'emergency'],
    '🛢': ['oil', 'drum', 'barrel', 'fuel', 'petroleum'],
    '💸': ['money', 'wings', 'fly', 'spend', 'waste'],
    '💵': ['dollar', 'money', 'cash', 'bill', 'usd'],
    '💴': ['yen', 'money', 'cash', 'bill', 'japan'],
    '💶': ['euro', 'money', 'cash', 'bill', 'europe'],
    '💷': ['pound', 'money', 'cash', 'bill', 'gbp', 'uk'],
    '🪙': ['coin', 'money', 'gold', 'currency'],
    '💰': ['money', 'bag', 'rich', 'dollar', 'wealth'],
    '💳': ['credit', 'card', 'payment', 'bank', 'debit'],
    '📫': ['mailbox', 'mail', 'post', 'letter', 'flag up'],
    '📪': ['mailbox', 'mail', 'post', 'letter', 'flag down'],
    '📬': ['mailbox', 'mail', 'incoming', 'letter'],
    '📭': ['mailbox', 'mail', 'empty', 'letter'],
    '📦': ['package', 'box', 'parcel', 'delivery', 'shipping'],
    '📝': ['memo', 'note', 'write', 'pencil', 'paper'],
    '📋': ['clipboard', 'list', 'paste', 'document'],
    '📁': ['folder', 'file', 'directory', 'organize'],
    '📂': ['folder', 'open', 'file', 'directory'],
    '🗂': ['dividers', 'file', 'tabs', 'organize', 'index'],
    '📅': ['calendar', 'date', 'schedule', 'event', 'day'],
    '📆': ['calendar', 'date', 'tear off', 'schedule'],
    '🗒': ['notepad', 'spiral', 'note', 'write', 'memo'],
    '🗓': ['calendar', 'spiral', 'schedule', 'date', 'planner'],
    '📌': ['pin', 'pushpin', 'location', 'mark', 'tack'],
    '📍': ['pin', 'location', 'map', 'mark', 'red'],
    '📎': ['paperclip', 'clip', 'attach', 'office'],
    '🖇': ['paperclips', 'linked', 'attach', 'office'],
    '📏': ['ruler', 'straight', 'measure', 'length'],
    '📐': ['ruler', 'triangle', 'measure', 'angle', 'math'],
    '✂️': ['scissors', 'cut', 'trim', 'craft'],
    '🗃': ['card', 'file', 'box', 'index', 'organize'],
    '🗄': ['cabinet', 'file', 'office', 'storage', 'drawer'],
    '🗑': ['trash', 'can', 'waste', 'delete', 'garbage', 'bin'],
    '🔒': ['lock', 'locked', 'secure', 'closed', 'private'],
    '🔓': ['unlock', 'unlocked', 'open', 'access'],
    '🔏': ['lock', 'pen', 'privacy', 'secure'],
    '🔐': ['lock', 'key', 'secure', 'closed'],
    '🔑': ['key', 'lock', 'access', 'password', 'unlock'],
    '🗝': ['key', 'old', 'vintage', 'antique', 'lock'],
    '🔨': ['hammer', 'tool', 'build', 'nail', 'construct'],
    '🪓': ['axe', 'chop', 'wood', 'tool', 'hatchet'],
    '⛏': ['pickaxe', 'mine', 'dig', 'tool', 'rock'],
    '⚒': ['hammer', 'pick', 'tool', 'work', 'mine'],
    '🛠': ['tools', 'wrench', 'hammer', 'repair', 'build'],
    '🗡': ['dagger', 'knife', 'sword', 'blade', 'weapon'],
    '⚔️': ['swords', 'crossed', 'battle', 'fight', 'weapon'],
    '🔫': ['gun', 'pistol', 'water', 'toy', 'weapon'],
    '🛡': ['shield', 'protect', 'defense', 'guard'],
    '🪚': ['saw', 'carpentry', 'cut', 'wood', 'tool'],
    '🔧': ['wrench', 'tool', 'fix', 'repair', 'spanner'],
    '🪛': ['screwdriver', 'tool', 'fix', 'screw', 'repair'],
    '🔩': ['nut', 'bolt', 'screw', 'hardware', 'tool'],
    '⚙️': ['gear', 'cog', 'settings', 'mechanical', 'engine'],
    '🗜': ['clamp', 'compress', 'vice', 'tool'],
    '⚗️': ['alembic', 'chemistry', 'science', 'lab', 'distill'],
    '🧪': ['test', 'tube', 'science', 'lab', 'chemistry', 'experiment'],
    '🧫': ['petri', 'dish', 'science', 'lab', 'biology', 'bacteria'],
    '🔬': ['microscope', 'science', 'lab', 'research', 'biology'],
    '🔭': ['telescope', 'astronomy', 'space', 'stars', 'observe'],
    '💊': ['pill', 'medicine', 'drug', 'capsule', 'health'],
    '🩺': ['stethoscope', 'doctor', 'medical', 'health', 'hospital'],
    '🩻': ['xray', 'skeleton', 'bone', 'medical', 'scan'],
    '🩹': ['bandage', 'adhesive', 'wound', 'heal', 'first aid'],
    '🩸': ['blood', 'drop', 'red', 'donate', 'health'],
    '🧬': ['dna', 'genetics', 'science', 'biology', 'helix'],
    '🦠': ['microbe', 'germ', 'bacteria', 'virus', 'disease'],
    '🧲': ['magnet', 'attract', 'magnetic', 'metal'],
    '🚪': ['door', 'entrance', 'exit', 'room', 'open'],
    '🛋': ['couch', 'sofa', 'furniture', 'living room', 'seat'],
    '🪑': ['chair', 'seat', 'sit', 'furniture'],
    '🚽': ['toilet', 'bathroom', 'restroom', 'wc'],

};
