export const peopleKeywords: Record<string, string[]> = {
    // ── People ──
    '👋': ['wave', 'hello', 'hi', 'bye', 'greeting', 'hand'],
    '🤚': ['raised', 'back', 'hand', 'stop'],
    '🖐': ['hand', 'fingers', 'splayed', 'five', 'high five'],
    '✋': ['hand', 'stop', 'high five', 'raised'],
    '🖖': ['vulcan', 'spock', 'star trek', 'hand'],
    '👌': ['ok', 'okay', 'perfect', 'good', 'hand'],
    '🤌': ['pinched', 'fingers', 'italian', 'chef kiss'],
    '✌️': ['peace', 'victory', 'two', 'hand'],
    '🤞': ['crossed', 'fingers', 'luck', 'hope'],
    '🤟': ['love', 'you', 'hand', 'rock'],
    '🤘': ['rock', 'metal', 'horns', 'hand'],
    '🤙': ['call', 'shaka', 'hang loose', 'phone', 'hand'],
    '👈': ['point', 'left', 'hand', 'direction'],
    '👉': ['point', 'right', 'hand', 'direction'],
    '👆': ['point', 'up', 'hand', 'direction'],
    '🖕': ['middle', 'finger', 'hand', 'rude'],
    '👇': ['point', 'down', 'hand', 'direction'],
    '☝️': ['point', 'up', 'index', 'hand', 'one'],
    '👍': ['thumbs', 'up', 'like', 'approve', 'good', 'yes'],
    '👎': ['thumbs', 'down', 'dislike', 'bad', 'no'],
    '✊': ['fist', 'punch', 'power', 'strong'],
    '👊': ['fist', 'bump', 'punch', 'bro'],
    '🤛': ['fist', 'left', 'bump', 'punch'],
    '🤜': ['fist', 'right', 'bump', 'punch'],
    '👏': ['clap', 'applause', 'bravo', 'hands'],
    '🙌': ['raise', 'hands', 'celebration', 'hooray', 'praise'],
    '👐': ['open', 'hands', 'jazz'],
    '🤲': ['palms', 'up', 'hands', 'receive', 'pray'],
    '🙏': ['pray', 'please', 'thank', 'hope', 'namaste', 'hands'],
    '✍️': ['writing', 'hand', 'pen', 'compose'],
    '💪': ['muscle', 'strong', 'bicep', 'arm', 'power', 'flex'],
    '🦾': ['prosthetic', 'arm', 'mechanical', 'robot', 'strong'],
    '🦿': ['prosthetic', 'leg', 'mechanical', 'robot'],
    '🦵': ['leg', 'kick', 'limb'],
    '🦶': ['foot', 'kick', 'stomp', 'toe'],
    '👂': ['ear', 'listen', 'hear', 'sound'],
    '🦻': ['ear', 'hearing', 'aid', 'deaf', 'accessibility'],
    '👃': ['nose', 'smell', 'sniff'],
    '🫀': ['heart', 'organ', 'anatomical', 'body', 'pulse'],
    '🫁': ['lungs', 'breath', 'organ', 'body', 'respiratory'],
    '🧠': ['brain', 'mind', 'think', 'smart', 'intelligence'],
    '🦷': ['tooth', 'dental', 'dentist', 'teeth'],
    '🦴': ['bone', 'skeleton', 'body'],
    '👀': ['eyes', 'look', 'see', 'watch', 'stare'],
    '👁': ['eye', 'look', 'see', 'watch'],
    '👶': ['baby', 'child', 'infant', 'newborn', 'kid'],
    '🧒': ['child', 'kid', 'young', 'boy', 'girl'],
    '👦': ['boy', 'child', 'kid', 'young', 'male'],
    '👧': ['girl', 'child', 'kid', 'young', 'female'],
    '🧑': ['person', 'adult', 'human'],
    '👱': ['blond', 'blonde', 'person', 'hair'],
    '👨': ['man', 'male', 'adult', 'guy'],
    '🧔': ['beard', 'man', 'facial', 'hair'],
    '👩': ['woman', 'female', 'adult', 'lady'],
    '🧓': ['older', 'person', 'elder', 'senior'],
    '👴': ['old', 'man', 'grandfather', 'grandpa', 'elder'],
    '👵': ['old', 'woman', 'grandmother', 'grandma', 'elder'],
    '🙍': ['frown', 'person', 'sad', 'unhappy'],
    '🙎': ['pout', 'person', 'annoyed', 'upset'],
    '🙅': ['no', 'person', 'gesture', 'stop', 'deny'],
    '🙆': ['ok', 'person', 'gesture', 'yes', 'accept'],
    '💁': ['tipping', 'hand', 'person', 'information', 'sassy'],
    '🙋': ['raise', 'hand', 'person', 'volunteer', 'question'],
    '🧏': ['deaf', 'person', 'ear', 'accessibility'],
    '🙇': ['bow', 'person', 'respect', 'sorry', 'apology'],
    '🤦': ['facepalm', 'disbelief', 'shame', 'frustrated'],
    '🤷': ['shrug', 'idk', 'whatever', 'dunno'],
    '👮': ['police', 'officer', 'cop', 'law', 'security'],
    '🕵️': ['detective', 'spy', 'investigate', 'sleuth'],
    '💂': ['guard', 'soldier', 'royal', 'british'],
    '🥷': ['ninja', 'stealth', 'warrior', 'hidden'],
    '👷': ['construction', 'worker', 'builder', 'hard hat', 'engineer'],
    '🫅': ['royal', 'crown', 'king', 'queen', 'monarch'],
    '🤴': ['prince', 'royal', 'king', 'crown', 'boy'],
    '👸': ['princess', 'royal', 'queen', 'crown', 'girl', 'tiara'],

};
