export const smileysKeywords: Record<string, string[]> = {
    '😀': ['grinning', 'happy', 'smile', 'joy'],
    '😃': ['grinning', 'happy', 'smile', 'eyes'],
    '😄': ['grinning', 'happy', 'smile', 'laugh'],
    '😁': ['beaming', 'grin', 'happy', 'smile'],
    '😆': ['laughing', 'happy', 'grin', 'squint'],
    '😅': ['sweat', 'smile', 'nervous', 'relief'],
    '😂': ['joy', 'laugh', 'tears', 'crying', 'funny'],
    '🤣': ['rofl', 'laugh', 'rolling', 'funny', 'hilarious'],
    '😊': ['blush', 'smile', 'happy', 'warm'],
    '😇': ['angel', 'halo', 'innocent', 'holy'],
    '🙂': ['smile', 'slight', 'okay', 'neutral'],
    '🙃': ['upside', 'down', 'ironic', 'sarcastic'],
    '😉': ['wink', 'flirt', 'playful'],
    '😌': ['relieved', 'calm', 'peaceful', 'content'],
    '😍': ['heart', 'eyes', 'love', 'crush', 'adore'],
    '🥰': ['love', 'hearts', 'affection', 'adore', 'caring'],
    '😘': ['kiss', 'love', 'heart', 'blow'],
    '😗': ['kiss', 'smooch', 'lips'],
    '😙': ['kiss', 'smile', 'happy'],
    '😚': ['kiss', 'blush', 'affection'],
    '😋': ['yummy', 'delicious', 'tasty', 'tongue', 'food'],
    '😛': ['tongue', 'playful', 'silly'],
    '😝': ['tongue', 'squint', 'playful', 'silly'],
    '😜': ['wink', 'tongue', 'crazy', 'playful', 'silly'],
    '🤪': ['crazy', 'wild', 'zany', 'silly', 'goofy'],
    '🤨': ['raised', 'eyebrow', 'skeptical', 'suspicious', 'doubt'],
    '🧐': ['monocle', 'thinking', 'inspect', 'detective', 'curious'],
    '🤓': ['nerd', 'glasses', 'geek', 'smart', 'study'],
    '😎': ['cool', 'sunglasses', 'awesome', 'confident'],
    '🤩': ['star', 'struck', 'excited', 'amazing', 'wow'],
    '🥳': ['party', 'celebrate', 'birthday', 'confetti', 'hat'],
    '😏': ['smirk', 'smug', 'flirt', 'sly'],
    '😒': ['unamused', 'bored', 'annoyed', 'meh'],
    '😞': ['disappointed', 'sad', 'down', 'unhappy'],
    '😔': ['pensive', 'sad', 'thoughtful', 'reflective'],
    '😟': ['worried', 'concerned', 'anxious'],
    '😕': ['confused', 'puzzled', 'unsure'],
    '🙁': ['frown', 'sad', 'unhappy', 'slight'],
    '😣': ['persevere', 'struggle', 'frustrated'],
    '😖': ['confounded', 'frustrated', 'upset'],
    '😫': ['tired', 'exhausted', 'weary', 'fed up'],
    '😩': ['weary', 'tired', 'exhausted', 'whine'],
    '🥺': ['pleading', 'puppy', 'eyes', 'please', 'beg'],
    '😢': ['cry', 'sad', 'tear', 'upset'],
    '😭': ['crying', 'sob', 'sad', 'tears', 'wail'],
    '😤': ['angry', 'huff', 'steam', 'frustrated', 'mad'],
    '😠': ['angry', 'mad', 'annoyed', 'grumpy'],
    '😡': ['rage', 'angry', 'furious', 'mad', 'red'],
    '🤬': ['swearing', 'cursing', 'angry', 'symbols', 'mad'],
    '🤯': ['mind', 'blown', 'exploding', 'shocked', 'amazed'],
    '😳': ['flushed', 'embarrassed', 'shocked', 'surprised'],
    '🥵': ['hot', 'sweating', 'heat', 'warm', 'fever'],
    '🥶': ['cold', 'freezing', 'ice', 'frozen', 'winter'],
    '😱': ['scream', 'scared', 'horror', 'shocked', 'fear'],
    '😨': ['fearful', 'scared', 'afraid', 'frightened'],
    '😰': ['anxious', 'sweat', 'nervous', 'worried'],
    '😥': ['sad', 'relieved', 'disappointed', 'sweat'],
    '😓': ['downcast', 'sweat', 'hard', 'work'],
    '🤗': ['hug', 'hugging', 'embrace', 'warm', 'open'],
    '🤔': ['thinking', 'hmm', 'consider', 'wonder', 'ponder'],
    '🤭': ['giggle', 'cover', 'mouth', 'oops', 'shy'],
    '🤫': ['shush', 'quiet', 'secret', 'silence', 'hush'],
    '🤥': ['lying', 'pinocchio', 'liar', 'nose', 'dishonest'],
    '😶': ['mute', 'silent', 'speechless', 'quiet', 'no words'],
    '😐': ['neutral', 'blank', 'expressionless', 'straight'],
    '😑': ['expressionless', 'blank', 'deadpan', 'flat'],
    '😬': ['grimace', 'awkward', 'nervous', 'cringe', 'teeth'],
    '🙄': ['eye', 'roll', 'annoyed', 'bored', 'whatever'],
    '😯': ['hushed', 'surprised', 'stunned', 'wow'],
    '😦': ['frown', 'open', 'mouth', 'surprised'],
    '😧': ['anguished', 'worried', 'surprised'],
    '😮': ['open', 'mouth', 'surprised', 'wow', 'oh'],
    '😲': ['astonished', 'shocked', 'amazed', 'surprised'],
    '🥱': ['yawn', 'sleepy', 'tired', 'bored'],
    '😴': ['sleep', 'sleeping', 'zzz', 'tired', 'snore'],
    '😷': ['mask', 'sick', 'medical', 'covid', 'flu'],
    '🤒': ['thermometer', 'sick', 'fever', 'ill', 'temperature'],
    '🤕': ['bandage', 'hurt', 'injured', 'head', 'wound'],
    '🤢': ['nauseous', 'sick', 'green', 'queasy', 'vomit'],
    '🤮': ['vomit', 'throw up', 'sick', 'puke', 'nausea'],
    '🤧': ['sneeze', 'tissue', 'cold', 'sick', 'allergy'],
    '😵': ['dizzy', 'dead', 'unconscious', 'knocked out'],
    '🤐': ['zipper', 'mouth', 'sealed', 'quiet', 'secret'],
    '🥴': ['woozy', 'drunk', 'dizzy', 'tipsy', 'confused'],

};
