export const symbolsKeywords: Record<string, string[]> = {
    // ── Symbols ──
    '❤️': ['heart', 'red', 'love', 'like', 'valentine'],
    '🧡': ['heart', 'orange', 'love'],
    '💛': ['heart', 'yellow', 'love'],
    '💚': ['heart', 'green', 'love'],
    '💙': ['heart', 'blue', 'love'],
    '💜': ['heart', 'purple', 'love'],
    '🖤': ['heart', 'black', 'love', 'dark'],
    '🤍': ['heart', 'white', 'love', 'pure'],
    '🤎': ['heart', 'brown', 'love'],
    '💔': ['broken', 'heart', 'love', 'sad', 'heartbreak'],
    '❣️': ['heart', 'exclamation', 'love', 'heavy'],
    '💕': ['hearts', 'two', 'love', 'couple'],
    '💞': ['revolving', 'hearts', 'love', 'romance'],
    '💓': ['heartbeat', 'love', 'pulse', 'beating'],
    '💗': ['growing', 'heart', 'love', 'pink'],
    '💖': ['sparkling', 'heart', 'love', 'shine'],
    '💘': ['cupid', 'heart', 'arrow', 'love', 'valentine'],
    '💝': ['heart', 'ribbon', 'gift', 'love', 'chocolate'],
    '💟': ['heart', 'decoration', 'love', 'purple'],
    '☮️': ['peace', 'symbol', 'sign', 'hippie'],
    '✝️': ['cross', 'christian', 'religion', 'faith'],
    '☪️': ['star', 'crescent', 'islam', 'religion', 'muslim'],
    '🕉': ['om', 'hindu', 'religion', 'symbol', 'buddhism'],
    '☸️': ['wheel', 'dharma', 'buddhism', 'religion'],
    '🔯': ['star', 'david', 'hexagram', 'jewish'],
    '🪯': ['khanda', 'sikh', 'religion', 'symbol'],
    '☯️': ['yin', 'yang', 'balance', 'taoism', 'harmony'],
    '✡️': ['star', 'david', 'jewish', 'judaism', 'religion'],
    '🕎': ['menorah', 'jewish', 'hanukkah', 'candle', 'religion'],
    '☦️': ['orthodox', 'cross', 'christian', 'religion'],
    '🔱': ['trident', 'emblem', 'weapon', 'poseidon'],
    '⚜️': ['fleur', 'de', 'lis', 'scout', 'french'],
    '🔰': ['beginner', 'japanese', 'symbol', 'new', 'driver'],
    '♻️': ['recycle', 'green', 'environment', 'eco', 'reuse'],
    '✅': ['check', 'mark', 'done', 'yes', 'complete', 'success'],
    '❎': ['cross', 'mark', 'no', 'reject', 'square'],
    '🔴': ['circle', 'red', 'dot', 'record'],
    '🟠': ['circle', 'orange', 'dot'],
    '🟡': ['circle', 'yellow', 'dot'],
    '🟢': ['circle', 'green', 'dot', 'online'],
    '🔵': ['circle', 'blue', 'dot'],
    '🟣': ['circle', 'purple', 'dot'],
    '⚫': ['circle', 'black', 'dot'],
    '⚪': ['circle', 'white', 'dot'],
    '🟤': ['circle', 'brown', 'dot'],
    '🔺': ['triangle', 'red', 'up', 'arrow'],
    '🔻': ['triangle', 'red', 'down', 'arrow'],
    '💠': ['diamond', 'blue', 'shape', 'jewel'],
    '🔶': ['diamond', 'orange', 'large', 'shape'],
    '🔷': ['diamond', 'blue', 'large', 'shape'],
    '🔸': ['diamond', 'orange', 'small', 'shape'],
    '🔹': ['diamond', 'blue', 'small', 'shape'],
    '🔘': ['radio', 'button', 'circle', 'select'],
    '🔲': ['button', 'black', 'square'],
    '🔳': ['button', 'white', 'square'],
    '▪️': ['square', 'black', 'small'],
    '▫️': ['square', 'white', 'small'],
    '◾': ['square', 'black', 'medium small'],
    '◽': ['square', 'white', 'medium small'],
    '◼️': ['square', 'black', 'medium'],
    '◻️': ['square', 'white', 'medium'],
    '⬛': ['square', 'black', 'large'],
    '⬜': ['square', 'white', 'large'],
    '🟥': ['square', 'red'],
    '🟧': ['square', 'orange'],
    '🟨': ['square', 'yellow'],
    '🟩': ['square', 'green'],
    '🟦': ['square', 'blue'],
    '🟪': ['square', 'purple'],
    '⭕': ['circle', 'ring', 'round', 'outline'],
    '✔️': ['check', 'mark', 'done', 'yes', 'correct'],
    '❌': ['cross', 'no', 'wrong', 'delete', 'error', 'cancel'],
    '❓': ['question', 'mark', 'help', 'what', 'ask'],
    '❗': ['exclamation', 'mark', 'warning', 'alert', 'important'],
    '💯': ['hundred', 'percent', 'perfect', 'score', 'full'],
    '🔅': ['dim', 'brightness', 'low', 'light'],
    '🔆': ['bright', 'brightness', 'high', 'light'],
    '📛': ['name', 'badge', 'tag', 'label'],
    '⛔': ['prohibited', 'forbidden', 'stop', 'no entry', 'ban'],
    '🚫': ['prohibited', 'forbidden', 'no', 'ban', 'stop'],
    '💢': ['anger', 'symbol', 'mad', 'vein', 'annoyed'],
    '♨️': ['hot', 'springs', 'steam', 'spa', 'onsen'],
    '🚷': ['no', 'pedestrians', 'forbidden', 'walking', 'ban'],
    '📵': ['no', 'phone', 'mobile', 'forbidden', 'silent'],
    '🔞': ['eighteen', 'underage', 'adult', 'age', 'restricted'],
    '🔃': ['arrows', 'clockwise', 'refresh', 'reload', 'sync'],
    '🔄': ['arrows', 'counterclockwise', 'refresh', 'reload', 'sync'],
    '🔙': ['back', 'arrow', 'return', 'previous'],
    '🔚': ['end', 'arrow', 'finish'],
    '🔛': ['on', 'arrow', 'mark'],
    '🔜': ['soon', 'arrow', 'coming'],
    '🔝': ['top', 'arrow', 'up'],
    '🆗': ['ok', 'button', 'okay', 'accept', 'agree'],
    '🆕': ['new', 'button', 'fresh', 'latest'],
    '🆙': ['up', 'button', 'upgrade', 'update'],
    '🆒': ['cool', 'button', 'nice', 'awesome'],
    '🆓': ['free', 'button', 'gratis', 'no charge'],
    '🆖': ['ng', 'button', 'no good'],
    '📶': ['signal', 'bars', 'antenna', 'wireless', 'reception'],
    '🈴': ['japanese', 'passing', 'grade', 'symbol'],
    '🈵': ['japanese', 'full', 'no vacancy', 'symbol'],
    '🈹': ['japanese', 'discount', 'sale', 'symbol'],
    '🈲': ['japanese', 'prohibited', 'forbidden', 'symbol'],
};
