export const travelKeywords: Record<string, string[]> = {
    // ── Travel ──
    '🚗': ['car', 'automobile', 'vehicle', 'drive', 'red'],
    '🚕': ['taxi', 'cab', 'car', 'vehicle', 'yellow'],
    '🚙': ['suv', 'car', 'vehicle', 'drive', 'blue'],
    '🚌': ['bus', 'public', 'transport', 'vehicle'],
    '🚎': ['trolleybus', 'bus', 'transport', 'vehicle'],
    '🏎': ['racing', 'car', 'formula', 'speed', 'fast'],
    '🚓': ['police', 'car', 'cop', 'vehicle', 'patrol'],
    '🚑': ['ambulance', 'emergency', 'hospital', 'medical', 'vehicle'],
    '🚒': ['fire', 'engine', 'truck', 'emergency', 'vehicle'],
    '🚐': ['minibus', 'van', 'vehicle', 'transport'],
    '🛻': ['pickup', 'truck', 'vehicle', 'drive'],
    '🚚': ['truck', 'delivery', 'moving', 'vehicle'],
    '🚛': ['truck', 'semi', 'trailer', 'vehicle', 'cargo'],
    '🚜': ['tractor', 'farm', 'vehicle', 'agriculture'],
    '🏍': ['motorcycle', 'motorbike', 'vehicle', 'bike', 'ride'],
    '🛵': ['scooter', 'motor', 'vehicle', 'vespa', 'ride'],
    '🛺': ['rickshaw', 'auto', 'vehicle', 'tuk tuk'],
    '🚲': ['bicycle', 'bike', 'cycle', 'ride', 'pedal'],
    '🛴': ['scooter', 'kick', 'ride', 'vehicle'],
    '🛹': ['skateboard', 'skate', 'board', 'ride'],
    '🛼': ['roller', 'skate', 'skating', 'ride'],
    '🚁': ['helicopter', 'chopper', 'fly', 'aircraft'],
    '🛸': ['ufo', 'flying', 'saucer', 'alien', 'spaceship'],
    '✈️': ['airplane', 'plane', 'fly', 'travel', 'flight'],
    '🛩': ['airplane', 'small', 'plane', 'fly', 'private'],
    '🛫': ['departure', 'takeoff', 'plane', 'airplane', 'fly'],
    '🛬': ['arrival', 'landing', 'plane', 'airplane', 'fly'],
    '🚀': ['rocket', 'space', 'launch', 'ship', 'fast'],
    '🛶': ['canoe', 'boat', 'paddle', 'water', 'kayak'],
    '⛵': ['sailboat', 'boat', 'sail', 'wind', 'sea'],
    '🚤': ['speedboat', 'boat', 'fast', 'water'],
    '🛥': ['motorboat', 'boat', 'yacht', 'water'],
    '🛳': ['cruise', 'ship', 'boat', 'passenger', 'sea'],
    '⛴': ['ferry', 'boat', 'ship', 'transport', 'water'],
    '🚢': ['ship', 'boat', 'cruise', 'vessel', 'sea'],
    '⚓': ['anchor', 'ship', 'boat', 'port', 'dock'],
    '🗺': ['map', 'world', 'globe', 'travel', 'explore'],
    '🧭': ['compass', 'navigate', 'direction', 'explore'],
    '🏔': ['mountain', 'snow', 'peak', 'nature', 'landscape'],
    '⛰': ['mountain', 'nature', 'peak', 'landscape', 'hike'],
    '🌋': ['volcano', 'eruption', 'mountain', 'lava', 'nature'],
    '🗻': ['mount', 'fuji', 'mountain', 'japan', 'nature'],
    '🏕': ['camping', 'tent', 'outdoor', 'nature', 'camp'],
    '🏖': ['beach', 'umbrella', 'sand', 'ocean', 'vacation'],
    '🏜': ['desert', 'sand', 'dry', 'cactus', 'hot'],
    '🏝': ['island', 'tropical', 'palm', 'beach', 'paradise'],
    '🏞': ['national', 'park', 'nature', 'landscape', 'scenic'],
    '🏟': ['stadium', 'arena', 'sports', 'venue', 'field'],
    '🏛': ['classical', 'building', 'museum', 'greek', 'column', 'temple'],
    '🏗': ['construction', 'building', 'crane', 'site', 'work'],
    '🧱': ['brick', 'wall', 'building', 'construction'],
    '🏘': ['houses', 'neighborhood', 'suburban', 'residential'],
    '🏚': ['house', 'abandoned', 'derelict', 'old', 'haunted'],
    '🏠': ['house', 'home', 'building', 'residence'],
    '🏡': ['house', 'garden', 'home', 'yard', 'nature'],
    '🏢': ['office', 'building', 'work', 'business', 'corporate'],
    '🏣': ['post', 'office', 'japan', 'building', 'mail'],
    '🏤': ['post', 'office', 'building', 'mail', 'european'],
    '🏥': ['hospital', 'medical', 'building', 'health', 'doctor'],
    '🏦': ['bank', 'building', 'money', 'finance'],
    '🏨': ['hotel', 'building', 'accommodation', 'travel', 'stay'],
    '🏩': ['love', 'hotel', 'building', 'heart'],
    '🏪': ['convenience', 'store', 'shop', 'building', 'retail'],
    '🏫': ['school', 'building', 'education', 'institute', 'study'],
    '🏬': ['department', 'store', 'mall', 'shopping', 'building'],
    '🏭': ['factory', 'building', 'industry', 'manufacturing'],
    '🏯': ['castle', 'japanese', 'building', 'fortress'],
    '🏰': ['castle', 'european', 'building', 'fortress', 'medieval'],
    '💒': ['wedding', 'chapel', 'church', 'marriage', 'love'],
    '🗼': ['tower', 'tokyo', 'building', 'landmark'],
    '🗽': ['statue', 'liberty', 'new york', 'usa', 'landmark'],
    '⛪': ['church', 'chapel', 'building', 'religion', 'christian'],
    '🕌': ['mosque', 'building', 'religion', 'islam', 'minaret'],
    '🛕': ['hindu', 'temple', 'building', 'religion'],
    '🗾': ['japan', 'map', 'country', 'asia'],

};
