import React, { useMemo, useState } from 'react';

import { EMOJI_KEYWORDS } from './emojiKeywords';
import { Search } from '../Search';

import './EmojiPicker.scss';

interface EmojiCategory {
    id: string;
    icon: string;
    name: string;
    emojis: string[];
}

const CATEGORIES: EmojiCategory[] = [
    {
        id: 'smileys',
        icon: '😀',
        name: 'Smileys',
        emojis: [
            '😀',
            '😃',
            '😄',
            '😁',
            '😆',
            '😅',
            '😂',
            '🤣',
            '😊',
            '😇',
            '🙂',
            '🙃',
            '😉',
            '😌',
            '😍',
            '🥰',
            '😘',
            '😗',
            '😙',
            '😚',
            '😋',
            '😛',
            '😝',
            '😜',
            '🤪',
            '🤨',
            '🧐',
            '🤓',
            '😎',
            '🤩',
            '🥳',
            '😏',
            '😒',
            '😞',
            '😔',
            '😟',
            '😕',
            '🙁',
            '😣',
            '😖',
            '😫',
            '😩',
            '🥺',
            '😢',
            '😭',
            '😤',
            '😠',
            '😡',
            '🤬',
            '🤯',
            '😳',
            '🥵',
            '🥶',
            '😱',
            '😨',
            '😰',
            '😥',
            '😓',
            '🤗',
            '🤔',
            '🤭',
            '🤫',
            '🤥',
            '😶',
            '😐',
            '😑',
            '😬',
            '🙄',
            '😯',
            '😦',
            '😧',
            '😮',
            '😲',
            '🥱',
            '😴',
            '😷',
            '🤒',
            '🤕',
            '🤢',
            '🤮',
            '🤧',
            '😵',
            '🤐',
            '🥴',
        ],
    },
    {
        id: 'people',
        icon: '👋',
        name: 'People',
        emojis: [
            '👋',
            '🤚',
            '🖐',
            '✋',
            '🖖',
            '👌',
            '🤌',
            '✌️',
            '🤞',
            '🤟',
            '🤘',
            '🤙',
            '👈',
            '👉',
            '👆',
            '🖕',
            '👇',
            '☝️',
            '👍',
            '👎',
            '✊',
            '👊',
            '🤛',
            '🤜',
            '👏',
            '🙌',
            '👐',
            '🤲',
            '🙏',
            '✍️',
            '💪',
            '🦾',
            '🦿',
            '🦵',
            '🦶',
            '👂',
            '🦻',
            '👃',
            '🫀',
            '🫁',
            '🧠',
            '🦷',
            '🦴',
            '👀',
            '👁',
            '👶',
            '🧒',
            '👦',
            '👧',
            '🧑',
            '👱',
            '👨',
            '🧔',
            '👩',
            '🧓',
            '👴',
            '👵',
            '🙍',
            '🙎',
            '🙅',
            '🙆',
            '💁',
            '🙋',
            '🧏',
            '🙇',
            '🤦',
            '🤷',
            '👮',
            '🕵️',
            '💂',
            '🥷',
            '👷',
            '🫅',
            '🤴',
            '👸',
        ],
    },
    {
        id: 'animals',
        icon: '🐶',
        name: 'Animals',
        emojis: [
            '🐶',
            '🐱',
            '🐭',
            '🐹',
            '🐰',
            '🦊',
            '🐻',
            '🐼',
            '🐻‍❄️',
            '🐨',
            '🐯',
            '🦁',
            '🐮',
            '🐷',
            '🐸',
            '🐵',
            '🙈',
            '🙉',
            '🙊',
            '🐔',
            '🐧',
            '🐦',
            '🐤',
            '🦆',
            '🦅',
            '🦉',
            '🦇',
            '🐺',
            '🐗',
            '🐴',
            '🦄',
            '🐝',
            '🪱',
            '🐛',
            '🦋',
            '🐌',
            '🐞',
            '🐜',
            '🪲',
            '🦟',
            '🦗',
            '🕷',
            '🦂',
            '🐢',
            '🐍',
            '🦎',
            '🦖',
            '🦕',
            '🐙',
            '🦑',
            '🦐',
            '🦞',
            '🦀',
            '🐡',
            '🐠',
            '🐟',
            '🐬',
            '🐳',
            '🐋',
            '🦈',
            '🐊',
            '🐅',
            '🐆',
            '🦓',
            '🦍',
            '🦧',
            '🦣',
            '🐘',
            '🦛',
            '🦏',
            '🐪',
            '🐫',
            '🦒',
            '🦘',
            '🦬',
        ],
    },
    {
        id: 'food',
        icon: '🍎',
        name: 'Food',
        emojis: [
            '🍎',
            '🍊',
            '🍋',
            '🍇',
            '🍓',
            '🫐',
            '🍈',
            '🍒',
            '🍑',
            '🥭',
            '🍍',
            '🥥',
            '🥝',
            '🍅',
            '🍆',
            '🥑',
            '🥦',
            '🥬',
            '🥒',
            '🌶',
            '🫑',
            '🧄',
            '🧅',
            '🥔',
            '🍠',
            '🥐',
            '🥯',
            '🍞',
            '🥖',
            '🥨',
            '🧀',
            '🥚',
            '🍳',
            '🧈',
            '🥞',
            '🧇',
            '🥓',
            '🥩',
            '🍗',
            '🍖',
            '🌭',
            '🍔',
            '🍟',
            '🍕',
            '🌮',
            '🌯',
            '🫔',
            '🥙',
            '🧆',
            '🥚',
            '🍜',
            '🍝',
            '🍣',
            '🍱',
            '🍛',
            '🍲',
            '🍛',
            '🥘',
            '🫕',
            '🍱',
            '🍦',
            '🍧',
            '🍨',
            '🍩',
            '🍪',
            '🎂',
            '🍰',
            '🧁',
            '🥧',
            '🍫',
            '🍬',
            '🍭',
            '🍮',
            '🍯',
            '🍵',
            '☕',
            '🧃',
            '🥤',
            '🧋',
            '🍺',
            '🍻',
            '🥂',
            '🍷',
            '🥃',
            '🍸',
            '🍹',
            '🧉',
            '🍾',
        ],
    },
    {
        id: 'travel',
        icon: '✈️',
        name: 'Travel',
        emojis: [
            '🚗',
            '🚕',
            '🚙',
            '🚌',
            '🚎',
            '🏎',
            '🚓',
            '🚑',
            '🚒',
            '🚐',
            '🛻',
            '🚚',
            '🚛',
            '🚜',
            '🏍',
            '🛵',
            '🛺',
            '🚲',
            '🛴',
            '🛹',
            '🛼',
            '🚁',
            '🛸',
            '✈️',
            '🛩',
            '🛫',
            '🛬',
            '🚀',
            '🛶',
            '⛵',
            '🚤',
            '🛥',
            '🛳',
            '⛴',
            '🚢',
            '⚓',
            '🗺',
            '🧭',
            '🏔',
            '⛰',
            '🌋',
            '🗻',
            '🏕',
            '🏖',
            '🏜',
            '🏝',
            '🏞',
            '🏟',
            '🏛',
            '🏗',
            '🧱',
            '🏘',
            '🏚',
            '🏠',
            '🏡',
            '🏢',
            '🏣',
            '🏤',
            '🏥',
            '🏦',
            '🏨',
            '🏩',
            '🏪',
            '🏫',
            '🏬',
            '🏭',
            '🏯',
            '🏰',
            '💒',
            '🗼',
            '🗽',
            '⛪',
            '🕌',
            '🛕',
            '🗾',
        ],
    },
    {
        id: 'activities',
        icon: '⚽',
        name: 'Activities',
        emojis: [
            '⚽',
            '🏀',
            '🏈',
            '⚾',
            '🥎',
            '🎾',
            '🏐',
            '🏉',
            '🥏',
            '🎱',
            '🏓',
            '🏸',
            '🏒',
            '🏑',
            '🥍',
            '🏏',
            '🪃',
            '🥅',
            '⛳',
            '🪁',
            '🎣',
            '🤿',
            '🎽',
            '🎿',
            '🛷',
            '🥌',
            '🎯',
            '🪀',
            '🪆',
            '🎮',
            '🎲',
            '🧩',
            '🧸',
            '🪅',
            '🎭',
            '🎨',
            '🎬',
            '🎤',
            '🎧',
            '🎼',
            '🎵',
            '🎶',
            '🎷',
            '🎸',
            '🎹',
            '🎺',
            '🎻',
            '🥁',
            '🪘',
            '🎙',
            '📻',
            '🎚',
            '🎛',
            '📺',
            '📷',
            '📸',
            '🎥',
            '🎞',
            '📽',
            '🎦',
            '🏋️',
            '🤼',
            '🤸',
            '🤺',
            '⛹️',
            '🤾',
            '🏌️',
            '🏇',
            '🧘',
            '🏄',
            '🏊',
            '🤽',
            '🚣',
            '🧗',
            '🚵',
        ],
    },
    {
        id: 'objects',
        icon: '💡',
        name: 'Objects',
        emojis: [
            '⌚',
            '📱',
            '💻',
            '🖥',
            '🖨',
            '⌨️',
            '🖱',
            '🖲',
            '💾',
            '💿',
            '📀',
            '📷',
            '📸',
            '📹',
            '🎥',
            '📽',
            '📞',
            '☎️',
            '📺',
            '📻',
            '🧭',
            '⏰',
            '⌛',
            '⏳',
            '📡',
            '🔋',
            '🔌',
            '💡',
            '🔦',
            '🕯',
            '🪔',
            '🧯',
            '🛢',
            '💸',
            '💵',
            '💴',
            '💶',
            '💷',
            '🪙',
            '💰',
            '💳',
            '📫',
            '📪',
            '📬',
            '📭',
            '📦',
            '📝',
            '📋',
            '📁',
            '📂',
            '🗂',
            '📅',
            '📆',
            '🗒',
            '🗓',
            '📌',
            '📍',
            '📎',
            '🖇',
            '📏',
            '📐',
            '✂️',
            '🗃',
            '🗄',
            '🗑',
            '🔒',
            '🔓',
            '🔏',
            '🔐',
            '🔑',
            '🗝',
            '🔨',
            '🪓',
            '⛏',
            '⚒',
            '🛠',
            '🗡',
            '⚔️',
            '🔫',
            '🛡',
            '🪚',
            '🔧',
            '🪛',
            '🔩',
            '⚙️',
            '🗜',
            '⚗️',
            '🧪',
            '🧫',
            '🔬',
            '🔭',
            '📡',
            '💊',
            '🩺',
            '🩻',
            '🩹',
            '🩸',
            '🧬',
            '🦠',
            '🧲',
            '🧱',
            '🚪',
            '🛋',
            '🪑',
            '🚽',
        ],
    },
    {
        id: 'symbols',
        icon: '❤️',
        name: 'Symbols',
        emojis: [
            '❤️',
            '🧡',
            '💛',
            '💚',
            '💙',
            '💜',
            '🖤',
            '🤍',
            '🤎',
            '💔',
            '❣️',
            '💕',
            '💞',
            '💓',
            '💗',
            '💖',
            '💘',
            '💝',
            '💟',
            '☮️',
            '✝️',
            '☪️',
            '🕉',
            '☸️',
            '🔯',
            '🪯',
            '☯️',
            '✡️',
            '🕎',
            '☦️',
            '🔱',
            '⚜️',
            '🔰',
            '♻️',
            '✅',
            '❎',
            '🔴',
            '🟠',
            '🟡',
            '🟢',
            '🔵',
            '🟣',
            '⚫',
            '⚪',
            '🟤',
            '🔺',
            '🔻',
            '💠',
            '🔶',
            '🔷',
            '🔸',
            '🔹',
            '🔘',
            '🔲',
            '🔳',
            '▪️',
            '▫️',
            '◾',
            '◽',
            '◼️',
            '◻️',
            '⬛',
            '⬜',
            '🟥',
            '🟧',
            '🟨',
            '🟩',
            '🟦',
            '🟪',
            '⭕',
            '✔️',
            '❌',
            '❓',
            '❗',
            '💯',
            '🔅',
            '🔆',
            '🔱',
            '📛',
            '🔰',
            '⛔',
            '🚫',
            '💢',
            '♨️',
            '🚷',
            '📵',
            '🔞',
            '🔃',
            '🔄',
            '🔙',
            '🔚',
            '🔛',
            '🔜',
            '🔝',
            '🆗',
            '🆕',
            '🆙',
            '🆒',
            '🆓',
            '🆖',
            '📶',
            '🈴',
            '🈵',
            '🈹',
            '🈲',
        ],
    },
];

export interface EmojiPickerProps {
    value?: string;
    onChange?: (emoji: string) => void;
}

export const EmojiPicker: React.FC<EmojiPickerProps> = ({ value, onChange }) => {
    const [search, setSearch] = useState('');
    const [activeCategory, setActiveCategory] = useState(CATEGORIES[0].id);

    const filteredEmojis = useMemo(() => {
        if (!search.trim()) return null;
        const term = search.toLowerCase();
        return CATEGORIES.flatMap(cat =>
            cat.emojis.filter(emoji => {
                const keywords = EMOJI_KEYWORDS[emoji];
                return keywords?.some(kw => kw.includes(term)) || cat.name.toLowerCase().includes(term);
            })
        );
    }, [search]);

    const displayEmojis = filteredEmojis ?? CATEGORIES.find(c => c.id === activeCategory)?.emojis ?? [];

    return (
        <div className="emoji-picker">
            <div className="emoji-picker__search">
                <Search placeholder="Search emoji..." value={search} onChange={setSearch} autoFocus />
            </div>

            {!filteredEmojis && (
                <div className="emoji-picker__categories">
                    {CATEGORIES.map(cat => (
                        <button
                            key={cat.id}
                            className={`emoji-picker__cat-btn${activeCategory === cat.id ? ' is-active' : ''}`}
                            title={cat.name}
                            onClick={() => setActiveCategory(cat.id)}
                        >
                            {cat.icon}
                        </button>
                    ))}
                </div>
            )}

            <div className="emoji-picker__grid">
                {displayEmojis.length === 0 ? (
                    <p className="emoji-picker__empty">No results</p>
                ) : (
                    displayEmojis.map((emoji, i) => (
                        <button key={i} className={`emoji-picker__emoji${value === emoji ? ' is-selected' : ''}`} onClick={() => onChange?.(emoji)}>
                            {emoji}
                        </button>
                    ))
                )}
            </div>
        </div>
    );
};
