export const EMOJI_KEYWORDS: Record<string, string[]> = {
    // ── Smileys ──
    '😀': ['grinning', 'happy', 'smile', 'joy'],
    '😃': ['grinning', 'happy', 'smile', 'eyes'],
    '😄': ['grinning', 'happy', 'smile', 'laugh'],
    '😁': ['beaming', 'grin', 'happy', 'smile'],
    '😆': ['laughing', 'happy', 'grin', 'squint'],
    '😅': ['sweat', 'smile', 'nervous', 'relief'],
    '😂': ['joy', 'laugh', 'tears', 'crying', 'funny'],
    '🤣': ['rofl', 'laugh', 'rolling', 'funny', 'hilarious'],
    '😊': ['blush', 'smile', 'happy', 'warm'],
    '😇': ['angel', 'halo', 'innocent', 'holy'],
    '🙂': ['smile', 'slight', 'okay', 'neutral'],
    '🙃': ['upside', 'down', 'ironic', 'sarcastic'],
    '😉': ['wink', 'flirt', 'playful'],
    '😌': ['relieved', 'calm', 'peaceful', 'content'],
    '😍': ['heart', 'eyes', 'love', 'crush', 'adore'],
    '🥰': ['love', 'hearts', 'affection', 'adore', 'caring'],
    '😘': ['kiss', 'love', 'heart', 'blow'],
    '😗': ['kiss', 'smooch', 'lips'],
    '😙': ['kiss', 'smile', 'happy'],
    '😚': ['kiss', 'blush', 'affection'],
    '😋': ['yummy', 'delicious', 'tasty', 'tongue', 'food'],
    '😛': ['tongue', 'playful', 'silly'],
    '😝': ['tongue', 'squint', 'playful', 'silly'],
    '😜': ['wink', 'tongue', 'crazy', 'playful', 'silly'],
    '🤪': ['crazy', 'wild', 'zany', 'silly', 'goofy'],
    '🤨': ['raised', 'eyebrow', 'skeptical', 'suspicious', 'doubt'],
    '🧐': ['monocle', 'thinking', 'inspect', 'detective', 'curious'],
    '🤓': ['nerd', 'glasses', 'geek', 'smart', 'study'],
    '😎': ['cool', 'sunglasses', 'awesome', 'confident'],
    '🤩': ['star', 'struck', 'excited', 'amazing', 'wow'],
    '🥳': ['party', 'celebrate', 'birthday', 'confetti', 'hat'],
    '😏': ['smirk', 'smug', 'flirt', 'sly'],
    '😒': ['unamused', 'bored', 'annoyed', 'meh'],
    '😞': ['disappointed', 'sad', 'down', 'unhappy'],
    '😔': ['pensive', 'sad', 'thoughtful', 'reflective'],
    '😟': ['worried', 'concerned', 'anxious'],
    '😕': ['confused', 'puzzled', 'unsure'],
    '🙁': ['frown', 'sad', 'unhappy', 'slight'],
    '😣': ['persevere', 'struggle', 'frustrated'],
    '😖': ['confounded', 'frustrated', 'upset'],
    '😫': ['tired', 'exhausted', 'weary', 'fed up'],
    '😩': ['weary', 'tired', 'exhausted', 'whine'],
    '🥺': ['pleading', 'puppy', 'eyes', 'please', 'beg'],
    '😢': ['cry', 'sad', 'tear', 'upset'],
    '😭': ['crying', 'sob', 'sad', 'tears', 'wail'],
    '😤': ['angry', 'huff', 'steam', 'frustrated', 'mad'],
    '😠': ['angry', 'mad', 'annoyed', 'grumpy'],
    '😡': ['rage', 'angry', 'furious', 'mad', 'red'],
    '🤬': ['swearing', 'cursing', 'angry', 'symbols', 'mad'],
    '🤯': ['mind', 'blown', 'exploding', 'shocked', 'amazed'],
    '😳': ['flushed', 'embarrassed', 'shocked', 'surprised'],
    '🥵': ['hot', 'sweating', 'heat', 'warm', 'fever'],
    '🥶': ['cold', 'freezing', 'ice', 'frozen', 'winter'],
    '😱': ['scream', 'scared', 'horror', 'shocked', 'fear'],
    '😨': ['fearful', 'scared', 'afraid', 'frightened'],
    '😰': ['anxious', 'sweat', 'nervous', 'worried'],
    '😥': ['sad', 'relieved', 'disappointed', 'sweat'],
    '😓': ['downcast', 'sweat', 'hard', 'work'],
    '🤗': ['hug', 'hugging', 'embrace', 'warm', 'open'],
    '🤔': ['thinking', 'hmm', 'consider', 'wonder', 'ponder'],
    '🤭': ['giggle', 'cover', 'mouth', 'oops', 'shy'],
    '🤫': ['shush', 'quiet', 'secret', 'silence', 'hush'],
    '🤥': ['lying', 'pinocchio', 'liar', 'nose', 'dishonest'],
    '😶': ['mute', 'silent', 'speechless', 'quiet', 'no words'],
    '😐': ['neutral', 'blank', 'expressionless', 'straight'],
    '😑': ['expressionless', 'blank', 'deadpan', 'flat'],
    '😬': ['grimace', 'awkward', 'nervous', 'cringe', 'teeth'],
    '🙄': ['eye', 'roll', 'annoyed', 'bored', 'whatever'],
    '😯': ['hushed', 'surprised', 'stunned', 'wow'],
    '😦': ['frown', 'open', 'mouth', 'surprised'],
    '😧': ['anguished', 'worried', 'surprised'],
    '😮': ['open', 'mouth', 'surprised', 'wow', 'oh'],
    '😲': ['astonished', 'shocked', 'amazed', 'surprised'],
    '🥱': ['yawn', 'sleepy', 'tired', 'bored'],
    '😴': ['sleep', 'sleeping', 'zzz', 'tired', 'snore'],
    '😷': ['mask', 'sick', 'medical', 'covid', 'flu'],
    '🤒': ['thermometer', 'sick', 'fever', 'ill', 'temperature'],
    '🤕': ['bandage', 'hurt', 'injured', 'head', 'wound'],
    '🤢': ['nauseous', 'sick', 'green', 'queasy', 'vomit'],
    '🤮': ['vomit', 'throw up', 'sick', 'puke', 'nausea'],
    '🤧': ['sneeze', 'tissue', 'cold', 'sick', 'allergy'],
    '😵': ['dizzy', 'dead', 'unconscious', 'knocked out'],
    '🤐': ['zipper', 'mouth', 'sealed', 'quiet', 'secret'],
    '🥴': ['woozy', 'drunk', 'dizzy', 'tipsy', 'confused'],

    // ── People ──
    '👋': ['wave', 'hello', 'hi', 'bye', 'greeting', 'hand'],
    '🤚': ['raised', 'back', 'hand', 'stop'],
    '🖐': ['hand', 'fingers', 'splayed', 'five', 'high five'],
    '✋': ['hand', 'stop', 'high five', 'raised'],
    '🖖': ['vulcan', 'spock', 'star trek', 'hand'],
    '👌': ['ok', 'okay', 'perfect', 'good', 'hand'],
    '🤌': ['pinched', 'fingers', 'italian', 'chef kiss'],
    '✌️': ['peace', 'victory', 'two', 'hand'],
    '🤞': ['crossed', 'fingers', 'luck', 'hope'],
    '🤟': ['love', 'you', 'hand', 'rock'],
    '🤘': ['rock', 'metal', 'horns', 'hand'],
    '🤙': ['call', 'shaka', 'hang loose', 'phone', 'hand'],
    '👈': ['point', 'left', 'hand', 'direction'],
    '👉': ['point', 'right', 'hand', 'direction'],
    '👆': ['point', 'up', 'hand', 'direction'],
    '🖕': ['middle', 'finger', 'hand', 'rude'],
    '👇': ['point', 'down', 'hand', 'direction'],
    '☝️': ['point', 'up', 'index', 'hand', 'one'],
    '👍': ['thumbs', 'up', 'like', 'approve', 'good', 'yes'],
    '👎': ['thumbs', 'down', 'dislike', 'bad', 'no'],
    '✊': ['fist', 'punch', 'power', 'strong'],
    '👊': ['fist', 'bump', 'punch', 'bro'],
    '🤛': ['fist', 'left', 'bump', 'punch'],
    '🤜': ['fist', 'right', 'bump', 'punch'],
    '👏': ['clap', 'applause', 'bravo', 'hands'],
    '🙌': ['raise', 'hands', 'celebration', 'hooray', 'praise'],
    '👐': ['open', 'hands', 'jazz'],
    '🤲': ['palms', 'up', 'hands', 'receive', 'pray'],
    '🙏': ['pray', 'please', 'thank', 'hope', 'namaste', 'hands'],
    '✍️': ['writing', 'hand', 'pen', 'compose'],
    '💪': ['muscle', 'strong', 'bicep', 'arm', 'power', 'flex'],
    '🦾': ['prosthetic', 'arm', 'mechanical', 'robot', 'strong'],
    '🦿': ['prosthetic', 'leg', 'mechanical', 'robot'],
    '🦵': ['leg', 'kick', 'limb'],
    '🦶': ['foot', 'kick', 'stomp', 'toe'],
    '👂': ['ear', 'listen', 'hear', 'sound'],
    '🦻': ['ear', 'hearing', 'aid', 'deaf', 'accessibility'],
    '👃': ['nose', 'smell', 'sniff'],
    '🫀': ['heart', 'organ', 'anatomical', 'body', 'pulse'],
    '🫁': ['lungs', 'breath', 'organ', 'body', 'respiratory'],
    '🧠': ['brain', 'mind', 'think', 'smart', 'intelligence'],
    '🦷': ['tooth', 'dental', 'dentist', 'teeth'],
    '🦴': ['bone', 'skeleton', 'body'],
    '👀': ['eyes', 'look', 'see', 'watch', 'stare'],
    '👁': ['eye', 'look', 'see', 'watch'],
    '👶': ['baby', 'child', 'infant', 'newborn', 'kid'],
    '🧒': ['child', 'kid', 'young', 'boy', 'girl'],
    '👦': ['boy', 'child', 'kid', 'young', 'male'],
    '👧': ['girl', 'child', 'kid', 'young', 'female'],
    '🧑': ['person', 'adult', 'human'],
    '👱': ['blond', 'blonde', 'person', 'hair'],
    '👨': ['man', 'male', 'adult', 'guy'],
    '🧔': ['beard', 'man', 'facial', 'hair'],
    '👩': ['woman', 'female', 'adult', 'lady'],
    '🧓': ['older', 'person', 'elder', 'senior'],
    '👴': ['old', 'man', 'grandfather', 'grandpa', 'elder'],
    '👵': ['old', 'woman', 'grandmother', 'grandma', 'elder'],
    '🙍': ['frown', 'person', 'sad', 'unhappy'],
    '🙎': ['pout', 'person', 'annoyed', 'upset'],
    '🙅': ['no', 'person', 'gesture', 'stop', 'deny'],
    '🙆': ['ok', 'person', 'gesture', 'yes', 'accept'],
    '💁': ['tipping', 'hand', 'person', 'information', 'sassy'],
    '🙋': ['raise', 'hand', 'person', 'volunteer', 'question'],
    '🧏': ['deaf', 'person', 'ear', 'accessibility'],
    '🙇': ['bow', 'person', 'respect', 'sorry', 'apology'],
    '🤦': ['facepalm', 'disbelief', 'shame', 'frustrated'],
    '🤷': ['shrug', 'idk', 'whatever', 'dunno'],
    '👮': ['police', 'officer', 'cop', 'law', 'security'],
    '🕵️': ['detective', 'spy', 'investigate', 'sleuth'],
    '💂': ['guard', 'soldier', 'royal', 'british'],
    '🥷': ['ninja', 'stealth', 'warrior', 'hidden'],
    '👷': ['construction', 'worker', 'builder', 'hard hat', 'engineer'],
    '🫅': ['royal', 'crown', 'king', 'queen', 'monarch'],
    '🤴': ['prince', 'royal', 'king', 'crown', 'boy'],
    '👸': ['princess', 'royal', 'queen', 'crown', 'girl', 'tiara'],

    // ── Animals ──
    '🐶': ['dog', 'puppy', 'pet', 'animal', 'cute'],
    '🐱': ['cat', 'kitten', 'pet', 'animal', 'cute'],
    '🐭': ['mouse', 'rat', 'rodent', 'animal'],
    '🐹': ['hamster', 'pet', 'rodent', 'animal', 'cute'],
    '🐰': ['rabbit', 'bunny', 'pet', 'animal', 'cute'],
    '🦊': ['fox', 'animal', 'wild', 'clever'],
    '🐻': ['bear', 'animal', 'wild', 'brown'],
    '🐼': ['panda', 'bear', 'animal', 'bamboo', 'china'],
    '🐻‍❄️': ['polar', 'bear', 'arctic', 'ice', 'white'],
    '🐨': ['koala', 'animal', 'australia', 'cute'],
    '🐯': ['tiger', 'animal', 'wild', 'cat', 'stripe'],
    '🦁': ['lion', 'animal', 'wild', 'king', 'mane'],
    '🐮': ['cow', 'animal', 'farm', 'milk', 'moo'],
    '🐷': ['pig', 'animal', 'farm', 'oink'],
    '🐸': ['frog', 'animal', 'toad', 'green', 'ribbit'],
    '🐵': ['monkey', 'animal', 'ape', 'primate'],
    '🙈': ['see', 'no', 'evil', 'monkey', 'eyes', 'hide'],
    '🙉': ['hear', 'no', 'evil', 'monkey', 'ears'],
    '🙊': ['speak', 'no', 'evil', 'monkey', 'mouth'],
    '🐔': ['chicken', 'hen', 'bird', 'farm', 'poultry'],
    '🐧': ['penguin', 'bird', 'animal', 'arctic', 'cold'],
    '🐦': ['bird', 'animal', 'fly', 'tweet'],
    '🐤': ['chick', 'baby', 'bird', 'chicken', 'cute'],
    '🦆': ['duck', 'bird', 'animal', 'quack', 'water'],
    '🦅': ['eagle', 'bird', 'animal', 'fly', 'america'],
    '🦉': ['owl', 'bird', 'night', 'wise', 'hoot'],
    '🦇': ['bat', 'animal', 'vampire', 'night', 'fly'],
    '🐺': ['wolf', 'animal', 'wild', 'howl'],
    '🐗': ['boar', 'pig', 'wild', 'animal'],
    '🐴': ['horse', 'animal', 'ride', 'pony'],
    '🦄': ['unicorn', 'horse', 'magic', 'fantasy', 'rainbow'],
    '🐝': ['bee', 'honey', 'insect', 'buzz', 'sting'],
    '🪱': ['worm', 'insect', 'earth', 'crawl'],
    '🐛': ['bug', 'insect', 'caterpillar', 'crawl'],
    '🦋': ['butterfly', 'insect', 'beautiful', 'wings', 'nature'],
    '🐌': ['snail', 'slow', 'animal', 'shell'],
    '🐞': ['ladybug', 'insect', 'beetle', 'red', 'luck'],
    '🐜': ['ant', 'insect', 'small', 'colony'],
    '🪲': ['beetle', 'insect', 'bug'],
    '🦟': ['mosquito', 'insect', 'bug', 'bite'],
    '🦗': ['cricket', 'insect', 'chirp', 'grasshopper'],
    '🕷': ['spider', 'insect', 'web', 'arachnid'],
    '🦂': ['scorpion', 'arachnid', 'sting', 'desert'],
    '🐢': ['turtle', 'tortoise', 'animal', 'slow', 'shell'],
    '🐍': ['snake', 'reptile', 'animal', 'hiss'],
    '🦎': ['lizard', 'reptile', 'animal', 'gecko'],
    '🦖': ['dinosaur', 'trex', 'extinct', 'reptile', 'jurassic'],
    '🦕': ['dinosaur', 'sauropod', 'extinct', 'brontosaurus'],
    '🐙': ['octopus', 'sea', 'ocean', 'tentacle', 'marine'],
    '🦑': ['squid', 'sea', 'ocean', 'tentacle', 'marine'],
    '🦐': ['shrimp', 'prawn', 'seafood', 'ocean'],
    '🦞': ['lobster', 'seafood', 'ocean', 'crustacean'],
    '🦀': ['crab', 'seafood', 'ocean', 'crustacean', 'beach'],
    '🐡': ['blowfish', 'puffer', 'fish', 'ocean', 'sea'],
    '🐠': ['fish', 'tropical', 'ocean', 'sea', 'aquarium'],
    '🐟': ['fish', 'ocean', 'sea', 'aquatic'],
    '🐬': ['dolphin', 'ocean', 'sea', 'marine', 'smart'],
    '🐳': ['whale', 'ocean', 'sea', 'marine', 'spout'],
    '🐋': ['whale', 'ocean', 'sea', 'marine', 'humpback'],
    '🦈': ['shark', 'ocean', 'sea', 'fish', 'danger'],
    '🐊': ['crocodile', 'alligator', 'reptile', 'swamp'],
    '🐅': ['tiger', 'animal', 'wild', 'cat', 'stripe'],
    '🐆': ['leopard', 'animal', 'wild', 'cat', 'spots', 'cheetah'],
    '🦓': ['zebra', 'animal', 'stripe', 'africa'],
    '🦍': ['gorilla', 'ape', 'primate', 'animal', 'strong'],
    '🦧': ['orangutan', 'ape', 'primate', 'animal'],
    '🦣': ['mammoth', 'elephant', 'extinct', 'ice age', 'woolly'],
    '🐘': ['elephant', 'animal', 'large', 'trunk', 'africa'],
    '🦛': ['hippo', 'hippopotamus', 'animal', 'water', 'africa'],
    '🦏': ['rhino', 'rhinoceros', 'animal', 'horn', 'africa'],
    '🐪': ['camel', 'desert', 'animal', 'hump'],
    '🐫': ['camel', 'desert', 'animal', 'two humps', 'bactrian'],
    '🦒': ['giraffe', 'animal', 'tall', 'africa', 'spots'],
    '🦘': ['kangaroo', 'animal', 'australia', 'jump', 'pouch'],
    '🦬': ['bison', 'buffalo', 'animal', 'wild'],

    // ── Food ──
    '🍎': ['apple', 'fruit', 'red', 'healthy'],
    '🍊': ['orange', 'tangerine', 'fruit', 'citrus'],
    '🍋': ['lemon', 'citrus', 'fruit', 'sour', 'yellow'],
    '🍇': ['grapes', 'fruit', 'wine', 'purple'],
    '🍓': ['strawberry', 'fruit', 'berry', 'red'],
    '🫐': ['blueberry', 'berry', 'fruit'],
    '🍈': ['melon', 'fruit', 'green', 'honeydew'],
    '🍒': ['cherry', 'cherries', 'fruit', 'red'],
    '🍑': ['peach', 'fruit', 'pink'],
    '🥭': ['mango', 'fruit', 'tropical'],
    '🍍': ['pineapple', 'fruit', 'tropical'],
    '🥥': ['coconut', 'fruit', 'tropical', 'palm'],
    '🥝': ['kiwi', 'fruit', 'green'],
    '🍅': ['tomato', 'vegetable', 'red', 'fruit'],
    '🍆': ['eggplant', 'aubergine', 'vegetable', 'purple'],
    '🥑': ['avocado', 'fruit', 'green', 'guacamole'],
    '🥦': ['broccoli', 'vegetable', 'green', 'healthy'],
    '🥬': ['leafy', 'green', 'vegetable', 'lettuce', 'salad'],
    '🥒': ['cucumber', 'vegetable', 'green', 'pickle'],
    '🌶': ['pepper', 'chili', 'hot', 'spicy', 'red'],
    '🫑': ['bell', 'pepper', 'vegetable', 'green'],
    '🧄': ['garlic', 'vegetable', 'cooking', 'spice'],
    '🧅': ['onion', 'vegetable', 'cooking', 'cry'],
    '🥔': ['potato', 'vegetable', 'starch', 'spud'],
    '🍠': ['sweet', 'potato', 'yam', 'vegetable'],
    '🥐': ['croissant', 'bread', 'pastry', 'french', 'breakfast'],
    '🥯': ['bagel', 'bread', 'breakfast'],
    '🍞': ['bread', 'loaf', 'toast', 'baking'],
    '🥖': ['baguette', 'bread', 'french'],
    '🥨': ['pretzel', 'bread', 'snack', 'salty'],
    '🧀': ['cheese', 'dairy', 'swiss', 'yellow'],
    '🥚': ['egg', 'food', 'breakfast', 'chicken'],
    '🍳': ['egg', 'fried', 'cooking', 'breakfast', 'pan'],
    '🧈': ['butter', 'dairy', 'spread', 'cooking'],
    '🥞': ['pancake', 'breakfast', 'stack', 'syrup'],
    '🧇': ['waffle', 'breakfast', 'syrup'],
    '🥓': ['bacon', 'meat', 'pork', 'breakfast'],
    '🥩': ['meat', 'steak', 'beef', 'cut'],
    '🍗': ['chicken', 'leg', 'poultry', 'drumstick', 'meat'],
    '🍖': ['meat', 'bone', 'rib'],
    '🌭': ['hotdog', 'sausage', 'fast food'],
    '🍔': ['burger', 'hamburger', 'fast food', 'cheeseburger'],
    '🍟': ['fries', 'french', 'chips', 'fast food', 'potato'],
    '🍕': ['pizza', 'slice', 'italian', 'cheese', 'fast food'],
    '🌮': ['taco', 'mexican', 'food', 'shell'],
    '🌯': ['burrito', 'wrap', 'mexican', 'food'],
    '🫔': ['tamale', 'mexican', 'food', 'corn'],
    '🥙': ['pita', 'falafel', 'kebab', 'wrap', 'stuffed'],
    '🧆': ['falafel', 'food', 'middle eastern', 'chickpea'],
    '🍜': ['noodles', 'ramen', 'soup', 'asian', 'bowl'],
    '🍝': ['spaghetti', 'pasta', 'italian', 'noodles'],
    '🍣': ['sushi', 'japanese', 'fish', 'rice'],
    '🍱': ['bento', 'box', 'japanese', 'lunch', 'meal'],
    '🍛': ['curry', 'rice', 'indian', 'food', 'spicy'],
    '🍲': ['stew', 'pot', 'soup', 'food', 'cooking'],
    '🥘': ['paella', 'pan', 'cooking', 'food', 'shallow'],
    '🫕': ['fondue', 'cheese', 'pot', 'swiss', 'melted'],
    '🍦': ['ice cream', 'cone', 'dessert', 'cold', 'sweet'],
    '🍧': ['shaved', 'ice', 'dessert', 'cold', 'sweet'],
    '🍨': ['ice cream', 'sundae', 'dessert', 'sweet'],
    '🍩': ['donut', 'doughnut', 'dessert', 'sweet', 'pastry'],
    '🍪': ['cookie', 'biscuit', 'dessert', 'sweet', 'baking'],
    '🎂': ['cake', 'birthday', 'candles', 'celebration', 'dessert'],
    '🍰': ['cake', 'slice', 'shortcake', 'dessert', 'sweet'],
    '🧁': ['cupcake', 'muffin', 'dessert', 'sweet', 'baking'],
    '🥧': ['pie', 'dessert', 'baking', 'apple'],
    '🍫': ['chocolate', 'bar', 'candy', 'sweet'],
    '🍬': ['candy', 'sweet', 'sugar', 'wrapped'],
    '🍭': ['lollipop', 'candy', 'sweet', 'sugar'],
    '🍮': ['pudding', 'custard', 'flan', 'dessert'],
    '🍯': ['honey', 'pot', 'sweet', 'bee'],
    '🍵': ['tea', 'cup', 'green', 'drink', 'hot'],
    '☕': ['coffee', 'cup', 'drink', 'hot', 'cafe', 'espresso'],
    '🧃': ['juice', 'box', 'drink', 'beverage'],
    '🥤': ['cup', 'straw', 'soda', 'drink', 'beverage'],
    '🧋': ['boba', 'bubble', 'tea', 'milk', 'drink'],
    '🍺': ['beer', 'mug', 'drink', 'alcohol', 'bar'],
    '🍻': ['beer', 'cheers', 'clink', 'drink', 'toast'],
    '🥂': ['champagne', 'cheers', 'toast', 'wine', 'celebrate'],
    '🍷': ['wine', 'glass', 'red', 'drink', 'alcohol'],
    '🥃': ['whiskey', 'tumbler', 'drink', 'alcohol', 'glass'],
    '🍸': ['cocktail', 'martini', 'drink', 'alcohol', 'glass'],
    '🍹': ['tropical', 'drink', 'cocktail', 'alcohol', 'umbrella'],
    '🧉': ['mate', 'drink', 'tea', 'argentina'],
    '🍾': ['champagne', 'bottle', 'celebrate', 'pop', 'cork'],

    // ── Travel ──
    '🚗': ['car', 'automobile', 'vehicle', 'drive', 'red'],
    '🚕': ['taxi', 'cab', 'car', 'vehicle', 'yellow'],
    '🚙': ['suv', 'car', 'vehicle', 'drive', 'blue'],
    '🚌': ['bus', 'public', 'transport', 'vehicle'],
    '🚎': ['trolleybus', 'bus', 'transport', 'vehicle'],
    '🏎': ['racing', 'car', 'formula', 'speed', 'fast'],
    '🚓': ['police', 'car', 'cop', 'vehicle', 'patrol'],
    '🚑': ['ambulance', 'emergency', 'hospital', 'medical', 'vehicle'],
    '🚒': ['fire', 'engine', 'truck', 'emergency', 'vehicle'],
    '🚐': ['minibus', 'van', 'vehicle', 'transport'],
    '🛻': ['pickup', 'truck', 'vehicle', 'drive'],
    '🚚': ['truck', 'delivery', 'moving', 'vehicle'],
    '🚛': ['truck', 'semi', 'trailer', 'vehicle', 'cargo'],
    '🚜': ['tractor', 'farm', 'vehicle', 'agriculture'],
    '🏍': ['motorcycle', 'motorbike', 'vehicle', 'bike', 'ride'],
    '🛵': ['scooter', 'motor', 'vehicle', 'vespa', 'ride'],
    '🛺': ['rickshaw', 'auto', 'vehicle', 'tuk tuk'],
    '🚲': ['bicycle', 'bike', 'cycle', 'ride', 'pedal'],
    '🛴': ['scooter', 'kick', 'ride', 'vehicle'],
    '🛹': ['skateboard', 'skate', 'board', 'ride'],
    '🛼': ['roller', 'skate', 'skating', 'ride'],
    '🚁': ['helicopter', 'chopper', 'fly', 'aircraft'],
    '🛸': ['ufo', 'flying', 'saucer', 'alien', 'spaceship'],
    '✈️': ['airplane', 'plane', 'fly', 'travel', 'flight'],
    '🛩': ['airplane', 'small', 'plane', 'fly', 'private'],
    '🛫': ['departure', 'takeoff', 'plane', 'airplane', 'fly'],
    '🛬': ['arrival', 'landing', 'plane', 'airplane', 'fly'],
    '🚀': ['rocket', 'space', 'launch', 'ship', 'fast'],
    '🛶': ['canoe', 'boat', 'paddle', 'water', 'kayak'],
    '⛵': ['sailboat', 'boat', 'sail', 'wind', 'sea'],
    '🚤': ['speedboat', 'boat', 'fast', 'water'],
    '🛥': ['motorboat', 'boat', 'yacht', 'water'],
    '🛳': ['cruise', 'ship', 'boat', 'passenger', 'sea'],
    '⛴': ['ferry', 'boat', 'ship', 'transport', 'water'],
    '🚢': ['ship', 'boat', 'cruise', 'vessel', 'sea'],
    '⚓': ['anchor', 'ship', 'boat', 'port', 'dock'],
    '🗺': ['map', 'world', 'globe', 'travel', 'explore'],
    '🧭': ['compass', 'navigate', 'direction', 'explore'],
    '🏔': ['mountain', 'snow', 'peak', 'nature', 'landscape'],
    '⛰': ['mountain', 'nature', 'peak', 'landscape', 'hike'],
    '🌋': ['volcano', 'eruption', 'mountain', 'lava', 'nature'],
    '🗻': ['mount', 'fuji', 'mountain', 'japan', 'nature'],
    '🏕': ['camping', 'tent', 'outdoor', 'nature', 'camp'],
    '🏖': ['beach', 'umbrella', 'sand', 'ocean', 'vacation'],
    '🏜': ['desert', 'sand', 'dry', 'cactus', 'hot'],
    '🏝': ['island', 'tropical', 'palm', 'beach', 'paradise'],
    '🏞': ['national', 'park', 'nature', 'landscape', 'scenic'],
    '🏟': ['stadium', 'arena', 'sports', 'venue', 'field'],
    '🏛': ['classical', 'building', 'museum', 'greek', 'column', 'temple'],
    '🏗': ['construction', 'building', 'crane', 'site', 'work'],
    '🧱': ['brick', 'wall', 'building', 'construction'],
    '🏘': ['houses', 'neighborhood', 'suburban', 'residential'],
    '🏚': ['house', 'abandoned', 'derelict', 'old', 'haunted'],
    '🏠': ['house', 'home', 'building', 'residence'],
    '🏡': ['house', 'garden', 'home', 'yard', 'nature'],
    '🏢': ['office', 'building', 'work', 'business', 'corporate'],
    '🏣': ['post', 'office', 'japan', 'building', 'mail'],
    '🏤': ['post', 'office', 'building', 'mail', 'european'],
    '🏥': ['hospital', 'medical', 'building', 'health', 'doctor'],
    '🏦': ['bank', 'building', 'money', 'finance'],
    '🏨': ['hotel', 'building', 'accommodation', 'travel', 'stay'],
    '🏩': ['love', 'hotel', 'building', 'heart'],
    '🏪': ['convenience', 'store', 'shop', 'building', 'retail'],
    '🏫': ['school', 'building', 'education', 'institute', 'study'],
    '🏬': ['department', 'store', 'mall', 'shopping', 'building'],
    '🏭': ['factory', 'building', 'industry', 'manufacturing'],
    '🏯': ['castle', 'japanese', 'building', 'fortress'],
    '🏰': ['castle', 'european', 'building', 'fortress', 'medieval'],
    '💒': ['wedding', 'chapel', 'church', 'marriage', 'love'],
    '🗼': ['tower', 'tokyo', 'building', 'landmark'],
    '🗽': ['statue', 'liberty', 'new york', 'usa', 'landmark'],
    '⛪': ['church', 'chapel', 'building', 'religion', 'christian'],
    '🕌': ['mosque', 'building', 'religion', 'islam', 'minaret'],
    '🛕': ['hindu', 'temple', 'building', 'religion'],
    '🗾': ['japan', 'map', 'country', 'asia'],

    // ── Activities ──
    '⚽': ['soccer', 'football', 'ball', 'sport', 'game'],
    '🏀': ['basketball', 'ball', 'sport', 'game', 'nba'],
    '🏈': ['football', 'american', 'ball', 'sport', 'nfl'],
    '⚾': ['baseball', 'ball', 'sport', 'game'],
    '🥎': ['softball', 'ball', 'sport', 'game'],
    '🎾': ['tennis', 'ball', 'sport', 'racket'],
    '🏐': ['volleyball', 'ball', 'sport', 'game'],
    '🏉': ['rugby', 'ball', 'sport', 'game'],
    '🥏': ['frisbee', 'disc', 'sport', 'flying'],
    '🎱': ['pool', 'billiards', 'ball', 'eight', 'game'],
    '🏓': ['ping', 'pong', 'table tennis', 'sport', 'paddle'],
    '🏸': ['badminton', 'racket', 'shuttlecock', 'sport'],
    '🏒': ['hockey', 'ice', 'stick', 'puck', 'sport'],
    '🏑': ['field', 'hockey', 'stick', 'sport'],
    '🥍': ['lacrosse', 'stick', 'sport'],
    '🏏': ['cricket', 'bat', 'sport', 'game'],
    '🪃': ['boomerang', 'throw', 'return', 'australia'],
    '🥅': ['goal', 'net', 'sport', 'score'],
    '⛳': ['golf', 'flag', 'hole', 'sport'],
    '🪁': ['kite', 'fly', 'wind', 'outdoor'],
    '🎣': ['fishing', 'rod', 'fish', 'hobby', 'outdoor'],
    '🤿': ['diving', 'mask', 'snorkel', 'swim', 'underwater'],
    '🎽': ['running', 'shirt', 'jersey', 'sport', 'athletic'],
    '🎿': ['ski', 'skiing', 'snow', 'winter', 'sport'],
    '🛷': ['sled', 'sledge', 'snow', 'winter', 'slide'],
    '🥌': ['curling', 'stone', 'ice', 'sport', 'winter'],
    '🎯': ['target', 'dart', 'bullseye', 'aim', 'goal'],
    '🪀': ['yoyo', 'toy', 'play', 'string'],
    '🪆': ['nesting', 'dolls', 'matryoshka', 'russian', 'toy'],
    '🎮': ['game', 'controller', 'gaming', 'video', 'play', 'console'],
    '🎲': ['dice', 'game', 'chance', 'luck', 'roll', 'board'],
    '🧩': ['puzzle', 'piece', 'jigsaw', 'game', 'solve'],
    '🧸': ['teddy', 'bear', 'toy', 'stuffed', 'plush', 'cute'],
    '🪅': ['pinata', 'party', 'candy', 'celebration'],
    '🎭': ['theater', 'drama', 'masks', 'performing', 'arts'],
    '🎨': ['art', 'paint', 'palette', 'creative', 'draw', 'color'],
    '🎬': ['movie', 'film', 'clapper', 'cinema', 'action'],
    '🎤': ['microphone', 'sing', 'karaoke', 'music', 'voice'],
    '🎧': ['headphones', 'music', 'listen', 'audio', 'earphones'],
    '🎼': ['music', 'score', 'notes', 'sheet', 'compose'],
    '🎵': ['music', 'note', 'song', 'melody', 'tune'],
    '🎶': ['music', 'notes', 'song', 'melody', 'tune'],
    '🎷': ['saxophone', 'sax', 'jazz', 'music', 'instrument'],
    '🎸': ['guitar', 'rock', 'music', 'instrument', 'string'],
    '🎹': ['piano', 'keyboard', 'music', 'instrument', 'keys'],
    '🎺': ['trumpet', 'brass', 'music', 'instrument', 'horn'],
    '🎻': ['violin', 'fiddle', 'music', 'instrument', 'string'],
    '🥁': ['drum', 'music', 'instrument', 'beat', 'percussion'],
    '🪘': ['drum', 'long', 'music', 'instrument', 'african'],
    '🎙': ['microphone', 'studio', 'record', 'podcast', 'radio'],
    '📻': ['radio', 'music', 'broadcast', 'listen'],
    '🎚': ['slider', 'level', 'audio', 'volume', 'control'],
    '🎛': ['knobs', 'control', 'dials', 'audio', 'mixing'],
    '📺': ['television', 'tv', 'screen', 'watch', 'show'],
    '📷': ['camera', 'photo', 'picture', 'photography'],
    '📸': ['camera', 'flash', 'photo', 'picture', 'snapshot'],
    '🎥': ['camera', 'movie', 'film', 'video', 'record'],
    '🎞': ['film', 'frames', 'movie', 'cinema', 'reel'],
    '📽': ['projector', 'film', 'movie', 'cinema', 'presentation'],
    '🎦': ['cinema', 'movie', 'theater', 'screen'],
    '🏋️': ['weightlifting', 'gym', 'exercise', 'strong', 'fitness'],
    '🤼': ['wrestling', 'sport', 'fight', 'grapple'],
    '🤸': ['cartwheel', 'gymnastics', 'acrobat', 'flip'],
    '🤺': ['fencing', 'sword', 'sport', 'duel'],
    '⛹️': ['basketball', 'bounce', 'dribble', 'sport'],
    '🤾': ['handball', 'sport', 'throw', 'ball'],
    '🏌️': ['golf', 'swing', 'club', 'sport'],
    '🏇': ['horse', 'racing', 'jockey', 'sport', 'ride'],
    '🧘': ['yoga', 'meditate', 'zen', 'lotus', 'mindfulness'],
    '🏄': ['surfing', 'surf', 'wave', 'ocean', 'beach'],
    '🏊': ['swimming', 'swim', 'pool', 'water', 'sport'],
    '🤽': ['water', 'polo', 'swim', 'sport', 'ball'],
    '🚣': ['rowing', 'boat', 'paddle', 'water', 'canoe'],
    '🧗': ['climbing', 'rock', 'sport', 'mountain', 'wall'],
    '🚵': ['mountain', 'biking', 'cycling', 'bike', 'sport'],

    // ── Objects ──
    '⌚': ['watch', 'time', 'clock', 'wrist', 'accessory'],
    '📱': ['phone', 'mobile', 'smartphone', 'cell', 'iphone'],
    '💻': ['laptop', 'computer', 'pc', 'mac', 'work'],
    '🖥': ['desktop', 'computer', 'monitor', 'screen', 'display'],
    '🖨': ['printer', 'print', 'paper', 'office'],
    '⌨️': ['keyboard', 'type', 'computer', 'input'],
    '🖱': ['mouse', 'computer', 'click', 'cursor'],
    '🖲': ['trackball', 'computer', 'input', 'device'],
    '💾': ['floppy', 'disk', 'save', 'storage', 'retro'],
    '💿': ['cd', 'disc', 'dvd', 'music', 'optical'],
    '📀': ['dvd', 'disc', 'movie', 'video', 'optical'],
    '📹': ['video', 'camera', 'camcorder', 'record'],
    '📞': ['telephone', 'phone', 'receiver', 'call'],
    '☎️': ['telephone', 'phone', 'vintage', 'call', 'retro'],
    '⏰': ['alarm', 'clock', 'time', 'wake', 'morning'],
    '⌛': ['hourglass', 'time', 'sand', 'timer', 'done'],
    '⏳': ['hourglass', 'time', 'sand', 'timer', 'flowing'],
    '📡': ['satellite', 'dish', 'signal', 'antenna', 'broadcast'],
    '🔋': ['battery', 'power', 'charge', 'energy'],
    '🔌': ['plug', 'electric', 'power', 'outlet', 'charge'],
    '💡': ['bulb', 'light', 'idea', 'bright', 'lamp'],
    '🔦': ['flashlight', 'torch', 'light', 'beam'],
    '🕯': ['candle', 'light', 'flame', 'wax'],
    '🪔': ['lamp', 'oil', 'diya', 'light', 'flame'],
    '🧯': ['fire', 'extinguisher', 'safety', 'emergency'],
    '🛢': ['oil', 'drum', 'barrel', 'fuel', 'petroleum'],
    '💸': ['money', 'wings', 'fly', 'spend', 'waste'],
    '💵': ['dollar', 'money', 'cash', 'bill', 'usd'],
    '💴': ['yen', 'money', 'cash', 'bill', 'japan'],
    '💶': ['euro', 'money', 'cash', 'bill', 'europe'],
    '💷': ['pound', 'money', 'cash', 'bill', 'gbp', 'uk'],
    '🪙': ['coin', 'money', 'gold', 'currency'],
    '💰': ['money', 'bag', 'rich', 'dollar', 'wealth'],
    '💳': ['credit', 'card', 'payment', 'bank', 'debit'],
    '📫': ['mailbox', 'mail', 'post', 'letter', 'flag up'],
    '📪': ['mailbox', 'mail', 'post', 'letter', 'flag down'],
    '📬': ['mailbox', 'mail', 'incoming', 'letter'],
    '📭': ['mailbox', 'mail', 'empty', 'letter'],
    '📦': ['package', 'box', 'parcel', 'delivery', 'shipping'],
    '📝': ['memo', 'note', 'write', 'pencil', 'paper'],
    '📋': ['clipboard', 'list', 'paste', 'document'],
    '📁': ['folder', 'file', 'directory', 'organize'],
    '📂': ['folder', 'open', 'file', 'directory'],
    '🗂': ['dividers', 'file', 'tabs', 'organize', 'index'],
    '📅': ['calendar', 'date', 'schedule', 'event', 'day'],
    '📆': ['calendar', 'date', 'tear off', 'schedule'],
    '🗒': ['notepad', 'spiral', 'note', 'write', 'memo'],
    '🗓': ['calendar', 'spiral', 'schedule', 'date', 'planner'],
    '📌': ['pin', 'pushpin', 'location', 'mark', 'tack'],
    '📍': ['pin', 'location', 'map', 'mark', 'red'],
    '📎': ['paperclip', 'clip', 'attach', 'office'],
    '🖇': ['paperclips', 'linked', 'attach', 'office'],
    '📏': ['ruler', 'straight', 'measure', 'length'],
    '📐': ['ruler', 'triangle', 'measure', 'angle', 'math'],
    '✂️': ['scissors', 'cut', 'trim', 'craft'],
    '🗃': ['card', 'file', 'box', 'index', 'organize'],
    '🗄': ['cabinet', 'file', 'office', 'storage', 'drawer'],
    '🗑': ['trash', 'can', 'waste', 'delete', 'garbage', 'bin'],
    '🔒': ['lock', 'locked', 'secure', 'closed', 'private'],
    '🔓': ['unlock', 'unlocked', 'open', 'access'],
    '🔏': ['lock', 'pen', 'privacy', 'secure'],
    '🔐': ['lock', 'key', 'secure', 'closed'],
    '🔑': ['key', 'lock', 'access', 'password', 'unlock'],
    '🗝': ['key', 'old', 'vintage', 'antique', 'lock'],
    '🔨': ['hammer', 'tool', 'build', 'nail', 'construct'],
    '🪓': ['axe', 'chop', 'wood', 'tool', 'hatchet'],
    '⛏': ['pickaxe', 'mine', 'dig', 'tool', 'rock'],
    '⚒': ['hammer', 'pick', 'tool', 'work', 'mine'],
    '🛠': ['tools', 'wrench', 'hammer', 'repair', 'build'],
    '🗡': ['dagger', 'knife', 'sword', 'blade', 'weapon'],
    '⚔️': ['swords', 'crossed', 'battle', 'fight', 'weapon'],
    '🔫': ['gun', 'pistol', 'water', 'toy', 'weapon'],
    '🛡': ['shield', 'protect', 'defense', 'guard'],
    '🪚': ['saw', 'carpentry', 'cut', 'wood', 'tool'],
    '🔧': ['wrench', 'tool', 'fix', 'repair', 'spanner'],
    '🪛': ['screwdriver', 'tool', 'fix', 'screw', 'repair'],
    '🔩': ['nut', 'bolt', 'screw', 'hardware', 'tool'],
    '⚙️': ['gear', 'cog', 'settings', 'mechanical', 'engine'],
    '🗜': ['clamp', 'compress', 'vice', 'tool'],
    '⚗️': ['alembic', 'chemistry', 'science', 'lab', 'distill'],
    '🧪': ['test', 'tube', 'science', 'lab', 'chemistry', 'experiment'],
    '🧫': ['petri', 'dish', 'science', 'lab', 'biology', 'bacteria'],
    '🔬': ['microscope', 'science', 'lab', 'research', 'biology'],
    '🔭': ['telescope', 'astronomy', 'space', 'stars', 'observe'],
    '💊': ['pill', 'medicine', 'drug', 'capsule', 'health'],
    '🩺': ['stethoscope', 'doctor', 'medical', 'health', 'hospital'],
    '🩻': ['xray', 'skeleton', 'bone', 'medical', 'scan'],
    '🩹': ['bandage', 'adhesive', 'wound', 'heal', 'first aid'],
    '🩸': ['blood', 'drop', 'red', 'donate', 'health'],
    '🧬': ['dna', 'genetics', 'science', 'biology', 'helix'],
    '🦠': ['microbe', 'germ', 'bacteria', 'virus', 'disease'],
    '🧲': ['magnet', 'attract', 'magnetic', 'metal'],
    '🚪': ['door', 'entrance', 'exit', 'room', 'open'],
    '🛋': ['couch', 'sofa', 'furniture', 'living room', 'seat'],
    '🪑': ['chair', 'seat', 'sit', 'furniture'],
    '🚽': ['toilet', 'bathroom', 'restroom', 'wc'],

    // ── Symbols ──
    '❤️': ['heart', 'red', 'love', 'like', 'valentine'],
    '🧡': ['heart', 'orange', 'love'],
    '💛': ['heart', 'yellow', 'love'],
    '💚': ['heart', 'green', 'love'],
    '💙': ['heart', 'blue', 'love'],
    '💜': ['heart', 'purple', 'love'],
    '🖤': ['heart', 'black', 'love', 'dark'],
    '🤍': ['heart', 'white', 'love', 'pure'],
    '🤎': ['heart', 'brown', 'love'],
    '💔': ['broken', 'heart', 'love', 'sad', 'heartbreak'],
    '❣️': ['heart', 'exclamation', 'love', 'heavy'],
    '💕': ['hearts', 'two', 'love', 'couple'],
    '💞': ['revolving', 'hearts', 'love', 'romance'],
    '💓': ['heartbeat', 'love', 'pulse', 'beating'],
    '💗': ['growing', 'heart', 'love', 'pink'],
    '💖': ['sparkling', 'heart', 'love', 'shine'],
    '💘': ['cupid', 'heart', 'arrow', 'love', 'valentine'],
    '💝': ['heart', 'ribbon', 'gift', 'love', 'chocolate'],
    '💟': ['heart', 'decoration', 'love', 'purple'],
    '☮️': ['peace', 'symbol', 'sign', 'hippie'],
    '✝️': ['cross', 'christian', 'religion', 'faith'],
    '☪️': ['star', 'crescent', 'islam', 'religion', 'muslim'],
    '🕉': ['om', 'hindu', 'religion', 'symbol', 'buddhism'],
    '☸️': ['wheel', 'dharma', 'buddhism', 'religion'],
    '🔯': ['star', 'david', 'hexagram', 'jewish'],
    '🪯': ['khanda', 'sikh', 'religion', 'symbol'],
    '☯️': ['yin', 'yang', 'balance', 'taoism', 'harmony'],
    '✡️': ['star', 'david', 'jewish', 'judaism', 'religion'],
    '🕎': ['menorah', 'jewish', 'hanukkah', 'candle', 'religion'],
    '☦️': ['orthodox', 'cross', 'christian', 'religion'],
    '🔱': ['trident', 'emblem', 'weapon', 'poseidon'],
    '⚜️': ['fleur', 'de', 'lis', 'scout', 'french'],
    '🔰': ['beginner', 'japanese', 'symbol', 'new', 'driver'],
    '♻️': ['recycle', 'green', 'environment', 'eco', 'reuse'],
    '✅': ['check', 'mark', 'done', 'yes', 'complete', 'success'],
    '❎': ['cross', 'mark', 'no', 'reject', 'square'],
    '🔴': ['circle', 'red', 'dot', 'record'],
    '🟠': ['circle', 'orange', 'dot'],
    '🟡': ['circle', 'yellow', 'dot'],
    '🟢': ['circle', 'green', 'dot', 'online'],
    '🔵': ['circle', 'blue', 'dot'],
    '🟣': ['circle', 'purple', 'dot'],
    '⚫': ['circle', 'black', 'dot'],
    '⚪': ['circle', 'white', 'dot'],
    '🟤': ['circle', 'brown', 'dot'],
    '🔺': ['triangle', 'red', 'up', 'arrow'],
    '🔻': ['triangle', 'red', 'down', 'arrow'],
    '💠': ['diamond', 'blue', 'shape', 'jewel'],
    '🔶': ['diamond', 'orange', 'large', 'shape'],
    '🔷': ['diamond', 'blue', 'large', 'shape'],
    '🔸': ['diamond', 'orange', 'small', 'shape'],
    '🔹': ['diamond', 'blue', 'small', 'shape'],
    '🔘': ['radio', 'button', 'circle', 'select'],
    '🔲': ['button', 'black', 'square'],
    '🔳': ['button', 'white', 'square'],
    '▪️': ['square', 'black', 'small'],
    '▫️': ['square', 'white', 'small'],
    '◾': ['square', 'black', 'medium small'],
    '◽': ['square', 'white', 'medium small'],
    '◼️': ['square', 'black', 'medium'],
    '◻️': ['square', 'white', 'medium'],
    '⬛': ['square', 'black', 'large'],
    '⬜': ['square', 'white', 'large'],
    '🟥': ['square', 'red'],
    '🟧': ['square', 'orange'],
    '🟨': ['square', 'yellow'],
    '🟩': ['square', 'green'],
    '🟦': ['square', 'blue'],
    '🟪': ['square', 'purple'],
    '⭕': ['circle', 'ring', 'round', 'outline'],
    '✔️': ['check', 'mark', 'done', 'yes', 'correct'],
    '❌': ['cross', 'no', 'wrong', 'delete', 'error', 'cancel'],
    '❓': ['question', 'mark', 'help', 'what', 'ask'],
    '❗': ['exclamation', 'mark', 'warning', 'alert', 'important'],
    '💯': ['hundred', 'percent', 'perfect', 'score', 'full'],
    '🔅': ['dim', 'brightness', 'low', 'light'],
    '🔆': ['bright', 'brightness', 'high', 'light'],
    '📛': ['name', 'badge', 'tag', 'label'],
    '⛔': ['prohibited', 'forbidden', 'stop', 'no entry', 'ban'],
    '🚫': ['prohibited', 'forbidden', 'no', 'ban', 'stop'],
    '💢': ['anger', 'symbol', 'mad', 'vein', 'annoyed'],
    '♨️': ['hot', 'springs', 'steam', 'spa', 'onsen'],
    '🚷': ['no', 'pedestrians', 'forbidden', 'walking', 'ban'],
    '📵': ['no', 'phone', 'mobile', 'forbidden', 'silent'],
    '🔞': ['eighteen', 'underage', 'adult', 'age', 'restricted'],
    '🔃': ['arrows', 'clockwise', 'refresh', 'reload', 'sync'],
    '🔄': ['arrows', 'counterclockwise', 'refresh', 'reload', 'sync'],
    '🔙': ['back', 'arrow', 'return', 'previous'],
    '🔚': ['end', 'arrow', 'finish'],
    '🔛': ['on', 'arrow', 'mark'],
    '🔜': ['soon', 'arrow', 'coming'],
    '🔝': ['top', 'arrow', 'up'],
    '🆗': ['ok', 'button', 'okay', 'accept', 'agree'],
    '🆕': ['new', 'button', 'fresh', 'latest'],
    '🆙': ['up', 'button', 'upgrade', 'update'],
    '🆒': ['cool', 'button', 'nice', 'awesome'],
    '🆓': ['free', 'button', 'gratis', 'no charge'],
    '🆖': ['ng', 'button', 'no good'],
    '📶': ['signal', 'bars', 'antenna', 'wireless', 'reception'],
    '🈴': ['japanese', 'passing', 'grade', 'symbol'],
    '🈵': ['japanese', 'full', 'no vacancy', 'symbol'],
    '🈹': ['japanese', 'discount', 'sale', 'symbol'],
    '🈲': ['japanese', 'prohibited', 'forbidden', 'symbol'],
};
